### ISSUE TITLE
par bounds when multipliers are used 

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#103]
Are the bounds for the multipliers or the raw parameters in `par_bounds_dict`, when `PstFromFlopyModel` is called.

**Comment by jtwhite79** [comment]
multipliers - all the parameters setup by `PstFromFlopyModel` are multipliers (except `HFB` - @mnfienen , why is that?)

**Comment by mnfienen-usgs** [comment]
good question - we could make the HFB multipliers for sure. When I implemented it I was keen on avoiding needing the apply method in the `forward_run` script, but that's not a big deal.
