### ISSUE TITLE
Is STR (stream flow package) supported currently?

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#107]
I have a STR package in the model. I have tried to include a multiplier for str.con by the following code.

`bc_props = []`

`bc_props.append(["str.cond",0])`

`mfp_boss = pyemu.helpers.PstFromFlopyModel(model=m,new_model_ws=new_model_ws,org_model_ws=temp_model_ws,mflist_waterbudget=False, pp_props=pp_props, 
obssim_smp_pairs = obssim_smp_pairs, zone_props=zone_props,                                           **spatial_list_props=bc_props,**                                          remove_existing=True,pp_space=5,par_bounds_dict = {"hk":[0.01,100.0]})`

I got the following error when I run it. It seems like PyEMU doesn't rewrite the STR file as it does for other packages, such as WEL and RCH. 
FileNotFoundError: [Errno 2] No such file or directory: 'template\\.\\STR_0000.dat'

**Comment by jwhite-usgs** [comment]
Does STR use the same flopy mflist type to store list directed input?  If so, then it could work.  But some of those more advanced packages use “special” input formats so STR may not follow the structure pyemu is expecting.
