### ISSUE TITLE
update kriging factors after update the pp pars ranges in the pst class

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#108]
How can I update the factor files with PyEMU after I change the parameter ranges of some pilot points? The initial factor files were generated automatically when PstFromFlopyModel was called.

**Comment by jtwhite79** [comment]
The grid-based kriging factors in generated in `pyemu.geostats.OrdinaryKrige.calc_factors_grid()`, following that call, the factors fie is written by `OrdinaryKrige.to_grid_factors_file()`.  Does that help?

**Comment by flydream0428** [comment]
Yes, thanks, Jeremy. For the future, we may add some lines in the pst class to let it update the factor files automatically when parameter ranges are changed.
