### ISSUE TITLE
Model calibration

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#109]
So I know it's much more useful to interrogate models and look at uncertainty than to history match fluxes and groundwater elevations, but.... client wants old fashioned calibration. At least I can look at uncertainty before and after calibration. 

This wasn't really touched on in the July course. Are there any examples of pyEMU being used for history matching? Or even a clue as to the command to do so?

Thanks,
Rebecca

**Comment by jtwhite79** [comment]
Essentially, pestpp-glm and pestpp-ies are history matching (calibrating - barf) when they adjust parameters to reproduce observed states.  With ies, the “base” realization is (in theory) the unbiased, minimum error variance parameter set.  With glm, just use the final parameter estimates for the same.

**Comment by RebeccaDoble** [comment]
OK. That's what I thought. But I still can't get my head around where to put my actual real physical (albeit uncertain and biased) measurements of groundwater head and flux. I'm trying to chuck them into pst.observation_data, but this keeps getting overwritten with model observations (was it John who started calling model outputs 'observations' to confuse 99% of all living groundwater modellers? because if it was, I'm going to have stern words with him) whenever I do anything.

**Comment by RebeccaDoble** [comment]
Actually, just found my coding error so that it is not overwritten, but I'm still not sure if I have by field observations in the correct location.

**Comment by jtwhite79** [comment]
That’s the tricky part with pest in general I think - it’s up to users to make sure the output from the model can and should be compared with the specified observation value in the control file.  It’s not easy to do from a mechanics standpoint.  And it will almost always require some kind of filtering/processing to remove unwanted signal components.  I wish I had an easier way to get this done...open to suggestions...

**Comment by wkitlasten** [comment]
On a side note, and to avoid any upset stomachs, what is a more acceptable
way to say "the model was calbrated to historical records of..."? I just
can't craft a suitable sounding sentence that includes any form of "history
matching."

Sent from my phone without spell checker. Please excuse my fat thumbs and
bad eyes.

**Comment by RebeccaDoble** [comment]
Probably: 'I kicked the parameters around a bit until they showed a crappy but un-improvable fit with the historical measured groundwater heads' sounds a bit sarcastic.

Perhaps change to 'parameters were modified to minimise (or provide one of many possible model realisations that minimised) the RMSE between model outputs and historical observations.'

**Comment by jtwhite79** [comment]
Someone once told me I should consult an over-imbibed homeless individual for help with my grammar so you don’t want my opinion here!

**Comment by RebeccaDoble** [comment]
@jtwhite79 Yeah, I'm not sure. I think it is very project dependent. What I would like is to be able to drag in a number of head and flux timeseries, and for <*magic*> to transform it into a dataframe with the correct observation titles, aggregated (or possibly interpolated) appropriately to the model output frequency, filtered to remove all the Nans and then linked with the appropriate model observations in pst.observation_data. 

I'm sure I could do that myself. It's just tedious. Is there something in common that all groundwater modellers do in this space? Surely head obs and flux obs are fairily commonly used?

**Comment by RebeccaDoble** [comment]
Plus add some what that makes it easy to extract and aggregate flux outputs from a cbc file. - Drains, ET, etc. Which is what I am about to attempt to do (agonisingly slowly and badly)

**Comment by RebeccaDoble** [comment]
Also, isn't it sleep time in the US?

**Comment by jtwhite79** [comment]
Your favorite utility (pyemu.gw_utils.setup_hds_timeseries()) can accept a cell budget file and “text” for what component your are after.

**Comment by RebeccaDoble** [comment]
Hurrah. Thanks. Good old hds_timeseries.

**Comment by oscarfasanchez** [comment]
> So I know it's much more useful to interrogate models and look at uncertainty than to history match fluxes and groundwater elevations, but.... client wants old fashioned calibration. At least I can look at uncertainty before and after calibration.
> 
> This wasn't really touched on in the July course. Are there any examples of pyEMU being used for history matching? Or even a clue as to the command to do so?
> 
> Thanks,
> Rebecca

Hi  did you find an example or something like that, I want to calibrate a model too and I'm lost

**Comment by jwhite-usgs** [comment]
pyEMU itself doesnt do any parameter adjustments for history matching.  Instead it sets up and post-processes PEST(_HP,++) analyses, including FOSM-based uncertainty and dataworth calcs.  

[https://github.com/mnfienen-usgs/GW1876/tree/fy20/activities_stpete/notebooks](https://github.com/mnfienen-usgs/GW1876/tree/fy20/activities_stpete/notebooks) - there is a sequence of jupyter notebooks here that walk thru setting up and history matching a synthetic transient model.  See the notebook_order.readme to instructions
