### ISSUE TITLE
More setup_hds_timeseries hurdles

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#111]
I'm wondering whether there have been any recent changes to setup_hds_timeseries lately that I somehow haven't captured in my latest download. 

I'm trying to extract drain data from the .DRN.cbc file, and I've got:

bin_file = os.path.join(m.model_ws,m.name+".DRN.cbc")
ts = pyemu.gw_utils.setup_hds_timeseries(hds_file = bin_file, kij_dict = drnInfo_T, prefix="drn", 
                                         include_path=True, model=m, text='          DRAINS', 
                                         postprocess_inact=None, precision = 'single')

which produces an unexpected keyword argument for both 'text' or 'precision'.  The pyemu 0.9 info says I can use 'text and 'precision'. 

Is this a version issue, or am I doing something wrong? I've tried taking both out, but without precision, it can't tell what precision to use (neither do I, but I figure it must be one of two, which isn't hard to test).

**Comment by jwhite-usgs** [comment]
I’m not sure what’s happening here.  Lemme look into it.

**Comment by RebeccaDoble** [comment]
OK. I found them in the 0.9 version guide, but I can't find the 0.9 version to download on this site, only up to 0.8. I'll have another look.

**Comment by RebeccaDoble** [comment]
Hey, is there any way to check the version of pyemu being used in the Jupyter notebook - perhaps the code is pointing to an earlier version in a different folder without me being aware of it.

**Comment by jwhite-usgs** [comment]
`pyemu.__version__` echos the version for me...

**Comment by RebeccaDoble** [comment]
'0+unknown' Ha!

**Comment by RebeccaDoble** [comment]
Just to confirm, I've downloaded the 0.8 version again today and still get the text and precision errors. It looks like it was updated May '19. Not sure if you've made any changes since then.

**Comment by jwhite-usgs** [comment]
[https://github.com/jtwhite79/pyemu/commit/2364dd9a7a03e8f41a832d703b403968f0948608](https://github.com/jtwhite79/pyemu/commit/2364dd9a7a03e8f41a832d703b403968f0948608)

I think the support for the `text` and `precision` args wasnt added until Sept `19

**Comment by RebeccaDoble** [comment]
Thanks! How can I access this version? I've only ever downloaded the releases.

**Comment by jwhite-usgs** [comment]
Sorry - forgot to push the tag (facepalm!).  The release for 0.9 is there now.

**Comment by RebeccaDoble** [comment]
Thanks. Got it, but it still doesn't seem to like the text and precision. Could it be because it is accessing the .DRN.cbc rather than straight .cbc file?
