### ISSUE TITLE
deal with ++ control variables using PyEMU

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#112]
Does the current version of PyEMU allow people to deal with the PEST++ variables, such as ies_parameter_ensemble() and sweep_parameter_csv_file()?

**Comment by jwhite-usgs** [comment]
Pst.pestpp_options is a dict of ++ key and value  So pst.pestpp_options[“ies_par_en”] = “prior.jcb” , etc.

**Comment by flydream0428** [comment]
@jwhite-usgs thanks. We really need a better doc for the powerful tool. I am happy to help when you plan to do this. :)

**Comment by jtwhite79** [comment]
I'm thinking the best way to document is with the online docs and example notebooks, similar to flopy - Im dedicated to keeping up the online docs up, they are much better than they used to be.  Open to other suggestions...

**Comment by flydream0428** [comment]
I like the flopy model. When I looked through  the repository, I feel I
need a high level introduction/tutorial notebook/doc to highlight the major
components/functions of pyemu. There are some introduction words in the
landing page. However, they are not connected to the
corresponding modules/classes.

Another thing I have noticed is that the links in the top two sections of
the online doc are dead. I am not sure if you are aware of this.

**Comment by wkitlasten** [comment]
When I started w pyemu (and flopy) I had a similar issue. I saw the power
but didn't really know how to go about accessing it other than to harass
Jeremy. I have heard similar comments from others who would benefit from
using it.

The examples/notebooks are essential but I agree a high level intro would
be helpful esp for those of us who struggle w reading python. I'm not sure
I know what it should look like, but I am more than happy to contribute.

Sent from my phone without spell checker. Please excuse my fat thumbs and
bad eyes.
