### ISSUE TITLE
Obtaining metrics for drawdown - with and without pumping example

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#115]
Hi all. I hope you've had a great Christmas and New Year.

I'm trying to get model uncertainty outputs for drawdown from my model through my botched up versions of the course notebooks. 

I realise that we did look at drawdown in the course, but I think that it was drawdown comparing heads at SP2 with heads at SP1 (change in head with time). My problem is looking at drawdown from a pumping scenario, so is comparing groundwater heads at the same time from two different models - control and treatment. 

Have you got any hints on how to call two model runs and subtract the difference between the heads? Do I have to run the model twice every time I do any processing, or is there some way of retaining the control information?

Thanks muchly.

**Comment by mnfienen** [comment]
Hey @RebeccaDoble 

You solved it in your speculation :). Basically, you just need to have both forward model runs called in your `forward_run` script (be that Python, batch or whatever). Or, you can set up both control and treatment as distinct stress periods in the same model. 

And then some script that calculates the differences the results of which get informed to PEST++ using a typical instruction file. Once you do all that, you have the ability to calculate and report uncertainty, etc.

Hope that helps. Happy New Year!

**Comment by jtwhite79** [comment]
@RebeccaDoble as with as this stuff, there are several ways to achieve your goal!  @mnfienen describes a perfectly viable way. 

 Another way is the have the control and treatment models setup with pest interfaces.  Then you run your parameter ensemble thru both the control and treatment models.  Assuming you have monitored the same outputs from both (and the outputs have the same observation names), then you can difference the output ensembles with pandas to calc drawdown.  Should be the same result, just depends on your workflow and what you see as the easiest path...

**Comment by mnfienen** [comment]
@jtwhite79 makes a great point with this alternative. Advantage here is if you want to work with just the control separately and add the treatment runs later.

**Comment by RebeccaDoble** [comment]
Thanks! I'll see what works out to be easier to implement.
