### ISSUE TITLE
dead links in the documents 

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#116]
Are you aware that all links in the top two sections of the document are dead?

**Comment by jtwhite79** [comment]
Yes I saw it recently.  The html and css renders and links fine in the browser locally - not sure what’s up...

**Comment by oscarfasanchez** [comment]
it's still broken :(

**Comment by oscarfasanchez** [comment]
all the documentation is dead , please help :(

**Comment by jwhite-usgs** [comment]
https://jtwhite79.github.io/pyemudoc/

If I follow the link on the github landing page, it still takes me to the docs and all of the documentation is still there, it’s just not formatted and the links at the top are broken.  Pull requests happy accepted.
