### ISSUE TITLE
absolute function on parameter value to compute Hill's style parameter sensitivity ?

### ISSUE THREAD

**Issue by apryet** [pypest/pyemu#117]
If we refer to Hill and Tiedman (2007), Eq. 4.3a p48, there should be an abs() function applied to parval1. Without it, sensitivity values are "upside down" when parameter values are negative. Thanks ! 

https://github.com/jtwhite79/pyemu/blob/8a889b7ca1b09c031bf3c9fed4e90070db8291f1/pyemu/la.py#L985

**Comment by jwhite-usgs** [comment]
I’ll take your word for it - I don’t have that book but that sounds reasonable.  PR’s accepted!
