### ISSUE TITLE
remove parameters and observations through TPL and INS files

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#123]
Hi Jeremy, is this function available in the developing branch? If not, I feel it's a useful thing to add. Although, we can do this through manipulating the dataframe directly, it's not handy. It requires extra effort to make the parameters consistent with the tpl files, as well as for the observations and ins files. I am happy to help if you think this is useful.

**Comment by jtwhite79** [comment]
It’s not available but would be a great addition!

**Comment by jtwhite79** [comment]
This has been implemented!
