### ISSUE TITLE
range and contribution parameters for geostatistical utilities  

### ISSUE THREAD

**Issue by flydream0428** [pypest/pyemu#124]
v = pyemu.utils.geostats.ExpVario(a=a,contribution=sill,anisotropy=1.0,bearing=0.0)
gs = pyemu.utils.geostats.GeoStruct(variograms=v,nugget=0,transform='log')

Is 'a' the effective range or the 'a' in the exponential variogram?
Does contribution contain the nugget contribution?

**Comment by jtwhite79** [comment]
The range of the exponential variogram is approx 3 times the "a" parameter (same as PEST and GSLIB).  The contribution of the nugget is only accounted for at the `GeoStruct` level (not for variograms individually)
