### ISSUE TITLE
Skip comments reading in model input files with Pandas

### ISSUE THREAD

**Issue by mnfienen-usgs** [pypest/pyemu#131]
Working with the general `PstFrom` functionality. I'm finding a problem with `pandas` version 1.0.1 in that I have files (external well files for individual stress periods in MODFLOW6, in this case) that have comments at the top. somehow, those are not being skipped when pandas reads in the file so the comments are interpreted as strings and makes all the indexing get read as strings. Not sure yet whether this will have ramifications on the application of the multipliers in forward run. Not that far yet. Also, tried using `mfile_skip='#'` to no avail.

Thanks!

**Comment by briochh** [comment]
Hi @mnfienen-usgs, Thanks for the effort in trying to beat up this `PstFrom()`. It sounds like you are fully succeeding. If you know how many comment lines there are in your input file, you should be able to set `mfile_skip=n`. These should then be read as a header and not as part of the pandas df. Maybe we also need to look into being able to specify a comment line identifier like you suggest, and get a bit smarter with the file reading.

**Comment by mnfienen-usgs** [comment]
Hey @briochh  - this generalization of the `PstFrom` stuff is a great contribution! Already stoked about it!

I suspect there are a few pandas reading things that would help, but adding an option like `comment_char=#` that you then pass to `read_csv` would be rad as a start. I just didn't want to break any of the reading logic. What do you think?

**Comment by briochh** [comment]
That should work off the bat so long as the comment char is at the start of the line. But if we are thinking about comment chars (which I think we should) we will probs need to support them elsewhere in lines --- for this we will need to get a bit smarter about how we read, unless we are happy to lose the comments, I which case I think we can pass `comment_char` to `comment` in `pandas_read_csv()`

**Comment by mnfienen-usgs** [comment]
excellent point! Supporting arbitrary comments would be good. But, then again, that also breaks the paradigm of a CSV tabular format, so maybe we are OK with just front-of-line comment for now.

**Comment by briochh** [comment]
@mnfienen-usgs, can you check if these changes work for you? Super thanks.

**Comment by mnfienen-usgs** [comment]
@briochh, looks like it worked in my case - thanks heaps! I had comments only in the header row and everything worked fine. The comments were not preserved when the output was written again, but not sure how important that is. BTW - I only tested adding a `comment_char` arg. Thanks for the edit!
