### ISSUE TITLE
Groupings for list-directed pars in `PstFrom`

### ISSUE THREAD

**Issue by mnfienen-usgs** [pypest/pyemu#132]
Another `PstFrom` issue. I have a couple cases of list parameters (e.g. lakebed conductance in a couple zones within a lake and stream reaches for SFR K) that it would be great to assign parameters to grouped by those zones. There is a column in each case by which unique values could be grouped and parameters assigned for each unique value. This was pretty easy to do outside `pyemu` but i think it's a valuable feature.

**Comment by jtwhite79** [comment]
I don’t know if this helps, but I was recently setting up sfr pars by including the reach number col in the index cols list so that the reach number makes it into the par name - is that what you are after?  Maybe you could include that zone column in the par name via index cols?

**Comment by briochh** [comment]
Hi @mnfienen-usgs, I think the most straight forward approach would be to follow as @jtwhite79 suggests. You can use that column as an `index_col` this will get passed through to the eventual parameter name which you can group however you like. Are you looking at passing a subgroup to a call of `add_parameters()` ? or enabling some sort of query to only set up pars where a certain condition is met in the dataframe that is read in? I think the latter would be handy could possibly be passed as a dictionary `{columnID: 'condition'}`.  Is this what you are thinking? Actually, I don't think we are supporting `use_rows` in `add_parameters()` yet so this would probably be the first step. That method is getting pretty heavy with arguments, may be worth looking into consolidating some.

**Comment by mnfienen-usgs** [comment]
I'll mess with that, but sounds like it should work. Thanks both of you!
