### ISSUE TITLE
res_phi_pie in plot_utils.py

### ISSUE THREAD

**Issue by mnfienen** [pypest/pyemu#173]
two quick things:

0) I think this:
```
    if "include_zero" not in kwargs or kwargs["include_zero"] is True:
        phi_comps = {k: phi_comps[k] for k in keys if phi_comps[k] > 0.0}
```
should be:
```
    if "include_zero" not in kwargs or kwargs["include_zero"] is False:
        phi_comps = {k: phi_comps[k] for k in keys if phi_comps[k] > 0.0}
```
As is, seems setting the `kwarg` 'include_zero' to `True` will actually exclude zero (like the docstring says - why do that anyway ?)

1) Propose another `kwarg` called `label_comps` that takes a list of potential components for the labels. Basically, any combo of  `['name', 'phi_comp', 'phi_percent']` since labels can get cluttered in the presence of hella obs groups. If no objection, I'll PR both of these

**Comment by jtwhite79** [comment]
sounds good to me!   I think you are right about the include_zero stuff and I agree that the labeling does get cluttered quickly with lots of groups...

**Comment by mnfienen** [comment]
right on. PR shortly
