### ISSUE TITLE
proper way to run tests locally

### ISSUE THREAD

**Issue by aleaf** [pypest/pyemu#179]
@jtwhite79 , I would like to work on the pst_from module (specifically, to get it to support data files within a subfolder, but maybe some other features as well), but first I'd like to be able to run the relevant tests to make sure I'm not breaking anything. I tried ``nosetests -v -w ./autotest pst_from_tests.py`` ( similar to what's in ``.travis.yml``), but am getting a bunch of errors, which mostly seem related to incorrect pathing to the executables. From ``.travis.yml``, it seems like the tests are supposed to be run from the root folder (looking in autotest), but the paths to the exes seem to imply that the cwd should be a subfolder in autotest?

I'm also having to change the test names to have "test" first (e.g. "test_freyberg") to be able to debug them individually in PyCharm (VS Code doesn't appear to discover them). Just wondering if you have any guidance on running the tests locally (and even better debugging within an IDE). Or what your strategy is if you've got a better one. Thanks.

**Comment by jtwhite79** [comment]
First of all, awesome!  Any enhancements to PstFrom (esp dealing with the pathing nightmare) are welcome.

I think if you add the pestpp binaries to the location of the bin_path variable (set at the top of pst_from_tests.py) nosetest should go with the way you are calling it from root.  You can call nosetests from within the autotest subdir if you leave off the -w flag.  I usually run the test scripts in pycharm from within the autotest subdir - just uncomment the test(s) you wanna run in pycharm.

**Comment by aleaf** [comment]
@jtwhite79 Thanks, can you remind me where I can get the pestpp mac binaries? I'm just seeing windows and linux in the releases at https://github.com/usgs/pestpp.

**Comment by jwhite-usgs** [comment]
well, this is where it gets tricky.  We've had some issues building fully-statically-linked binaries for mac.  @briochh was able to build the pestpp tools on mac using cmake and clang with these instructions:

[https://github.com/usgs/pestpp/blob/master/documentation/cmake.md](https://github.com/usgs/pestpp/blob/master/documentation/cmake.md)

I'll build them again with intel and send them your way to see if they work.  I think you need to have xcode installed (or at least the command line tools).  But it would be nice to see if they work for you  - @mnfienen previously reported they didnt work for him.

**Comment by aleaf** [comment]
ok, thanks. I can follow up with @mnfienen too. Have previously just gotten them from him but was hoping there was a more robust solution. I know there have been some issues.

**Comment by jwhite-usgs** [comment]
[pestpp-5.0.5-mac.tar.gz](https://github.com/pypest/pyemu/files/5453427/pestpp-5.0.5-mac.tar.gz)

These were build with intel c++.  Lemme know if they work

**Comment by mnfienen** [comment]
FWIW, most of these have worked in serial mode, but I had trouble with parallel run management. I'll try these as well. maybe we can get a build solution going along with the MODFLOW 6 team - I know they've been able to distribute Intel Mac binaries for the MODFLOW family of codes

**Comment by jtwhite79** [comment]
I'm keen to try to work it out but the mf6 guys only need for Fortran and c runtime libs (not pthreads, winsock etc) which makes static linking much much much easier!

**Comment by aleaf** [comment]
@jtwhite-usgs thanks, the above binaries seemed to work well on my mac, at least for the purpose of running the tests.
