### ISSUE TITLE
pst_from.add_parameters() for x-section model

### ISSUE THREAD

**Issue by rhugman** [pypest/pyemu#185]
Hello,

Cross-post from stackoverflow as recommended by @jtwhite79:
https://stackoverflow.com/questions/64662011/pyemu-add-parameters-from-a-modflow6-2d-cross-section-model

The following exception is returned when attempting to read parameters for a cross-section model:
```
C:\ProgramData\Anaconda3\lib\site-packages\pyemu\utils\pst_from.py in write_array_tpl(name, tpl_filename, suffix, par_type, zone_array, gpname, shape, longnames, fill_value, get_xy, input_filename, par_style)
   2679     if len(shape) != 2:
   2680         raise Exception(
-> 2681             "write_array_tpl() error: shape '{0}' not 2D" "".format(str(shape))
   2682         )
   2683 

Exception: write_array_tpl() error: shape '(200,)' not 2D
```

@jtwhite79 suggested it is probably related to how numpy loads a 1-D row of numbers.

**Comment by jtwhite79** [comment]
Sorry for the delay on this.  The issue is related to forcing the array to be loaded as 2D.  I've got a fix in now and if the tests pass, I'll merge it into the develop branch.

**Comment by jtwhite79** [comment]
#186 should have this fixed.  Let us know if not.

**Comment by rhugman** [comment]
Awesome, works. Thanks!
