### ISSUE TITLE
pst_from: forward_run.py with no multiplier parameters

### ISSUE THREAD

**Issue by rhugman** [pypest/pyemu#190]
The following line seems to be added to `forward_run.py` by default:

`pyemu.helpers.apply_list_and_array_pars(arr_par_file='mult2model_info.csv')`

An error is returned if no "multiplier" parameters are used (yes, yes, why whould you ever want to do such a thing?! :) ). Stripping that line from  `forward_run.py` resolves it.

```Traceback (most recent call last):
  File "forward_run.py", line 22, in <module>
    main()
  File "forward_run.py", line 16, in main
    pyemu.helpers.apply_list_and_array_pars(arr_par_file='mult2model_info.csv')
  File "c:\users\..\documents\github\pyemu\pyemu\utils\helpers.py", line 3592, in apply_list_and_array_pars
    apply_array_pars(arr_pars, chunk_len=chunk_len)
  File "c:\users\..\documents\github\pyemu\pyemu\utils\helpers.py", line 3762, in apply_array_pars
process 4  processed  0 process_model_file calls
    [xx.get() for xx in x]
  File "c:\users\..\documents\github\pyemu\pyemu\utils\helpers.py", line 3762, in <listcomp>
    [xx.get() for xx in x]
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
AttributeError: 'DataFrame' object has no attribute 'mlt_file'```

**Comment by jtwhite79** [comment]
@rhugman - Im trying to repro this problem but it looks like there is a conditional to handle the no-mlt_file situation on line [3616 of helpers.py](https://github.com/pypest/pyemu/blob/5e85fb60d2d9fbc428ee571a9b62e84ed4c7a558/pyemu/utils/helpers.py#L3616).  Are you using the develop branch?

**Comment by rhugman** [comment]
Yes I am. I just updated and am no longer able to reproduce the error. My bad - sorry about that.

**Comment by jtwhite79** [comment]
No probs @rhugman.  Please keep reporting any issues you find!
