### ISSUE TITLE
PstFrom.add_observations() - short names?

### ISSUE THREAD

**Issue by rhugman** [pypest/pyemu#195]
Hi,

I am using `pyemu.utils.PstFrom(longnames=False, ...)` and `pf.add_observations` with `index_cols` & `use_cols`, but getting very long observation names (including the string "usecol:" in the obs name). These can become very long, specially if the `index_col` is "time". 

Is there a way to force a maximum obs name length? Or for the user to provide obs names upfront? In particular to respect interoperability with PEST and its utilities?

Cheers

**Comment by jtwhite79** [comment]
@rhugman - you are right:  when requesting shortnames, PstFrom only made short par names.  Ive a patch testing for this now.  I agree it is important to support the 12 and 20 char names for interop - that was the idea with the longname flag!  I'll let you know once the tests pass.

**Comment by jtwhite79** [comment]
This should be fixed as of #197 - let us know if not...thanks again for your patience!

**Comment by rhugman** [comment]
Awesome, thanks. Seems to work so far!
