### ISSUE TITLE
Possible to add multi-thread functionality to apply_genericlist_pars()?

### ISSUE THREAD

**Issue by jknightusgs** [pypest/pyemu#206]
I'm wondering if apply_genericlist_pars() could be multi-threaded similarly to apply_array_pars(). I have about 300 of each style model input file. Using chunk_len=50 (6 threads) the array style files are produced in 2 minutes, while the list style files take more than 30 minutes to produce on a single thread.

**Comment by jtwhite79** [comment]
I think thats def doable.  I think @aymanalz has a PR coming that weaves in an option to control how many chunks/threads to use for array processing.  Once that comes in, I'll have a look at threading up the list processing (unless @briochh is getting bored on holiday?!)
