### ISSUE TITLE
py3.6 pandas issue on ghactions

### ISSUE THREAD

**Issue by jtwhite79** [pypest/pyemu#210]
@briochh - something is no worky with py3.6 and pandas.  Ok to drop coverage of py3.6?

**Comment by briochh** [comment]
yeah, looks like 3.6 is dropped from pandas and numpy (https://numpy.org/neps/nep-0029-deprecation_policy.html, https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html). I'm happy to follow these guys.

**Comment by briochh** [comment]
Should probably take a look at adding 3.9.
