### ISSUE TITLE
Possible to tie parameters with pf.add_parameters

### ISSUE THREAD

**Issue by Kimmvv** [pypest/pyemu#219]
Hello everyone,

I have encountered some problems with tied parameters. I have a transient groundwater model (MF-nwt). I want to add a constant multiplier to the groundwater recharge parameter that has spatial variability (zones), but does not vary with each timestep. I'm using the PstFrom module, because I read a note that said 'This is the way…' 

I have tried to use this. 
```
pf.add_parameters(filenames=rch[0]
                  ,par_type="constant"
                  ,zone_array=rch_zone
                  ,transform='None'
                  ,par_name_base="rch"
                  ,pargp="rch"
                  ,par_style='multiplier')

for irch in rch[1:]:  
    pf.add_parameters(filenames=irch
                  ,par_type="constant"
                  ,zone_array=rch_zone
                  ,transform='tied'
                  ,par_name_base="rch"
                  ,pargp="rch"
                  ,par_style='multiplier')
```
My thought was to add the first timestep parameter and then tie the remaining timesteps. But there is nowhere to assign which parameter to tie the other to. And when I attemp to do pf.build_pst() I get

```
noptmax:0, npar_adj:1, nnz_obs:624
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-28-755990eee6c9> in <module>
----> 1 pst = pf.build_pst()

~\.conda\envs\flowp\lib\site-packages\pyemu\utils\pst_from.py in build_pst(self, filename, update, version)
    626         self.pst = pst
    627 
--> 628         self.pst.write(filename, version=version)
    629         self.write_forward_run()
    630         pst.try_parse_name_metadata()

~\.conda\envs\flowp\lib\site-packages\pyemu\pst\pst_handler.py in write(self, new_filename, version)
   1610 
   1611         if version == 1:
-> 1612             return self._write_version1(new_filename=new_filename)
   1613         elif version == 2:
   1614             return self._write_version2(new_filename=new_filename)

~\.conda\envs\flowp\lib\site-packages\pyemu\pst\pst_handler.py in _write_version1(self, new_filename)
   1671                 self.tied,
   1672                 self.tied_format,
-> 1673                 self.tied_fieldnames,
   1674             )
   1675 

~\.conda\envs\flowp\lib\site-packages\pyemu\pst\pst_handler.py in _write_df(self, name, f, df, formatters, columns)
   1427             df.to_csv(csv_name)
   1428             raise Exception(
-> 1429                 "NaNs in {0} dataframe, csv written to {1}".format(name, csv_name)
   1430             )
   1431 

Exception: NaNs in tied parameter data dataframe, csv written to pst.tied_parameter_data.nans.csv
```
And the written csv looks like this 

,parnme,partied
rch1,rch1,
rch2,rch2,
rch3,rch3,

I've made my setup work by adding them all as constants and then manually editing (yuck!) the pest control file afterwards, but this is a cumbersome task.
It is likely that it is user error rather than a missing functionality.

Have a nice weekend!
Kim

**Comment by jtwhite79** [comment]
Ok I think you want a single constant recharge multiplier that applies to all stress periods (the same constant parameter get applied to every stress period).  If this is the case, then you can pass all the recharge arrays at once to `add_parameters()`:

```
pf.add_parameters(filenames=rch
                  ,par_type="constant"
                  ,zone_array=rch_zone
                  ,transform='None'
                  ,par_name_base="rch"
                  ,pargp="rch"
                  ,par_style='multiplier')
```
(assuming `rch` is a list of all the recharge array files)

This will setup a single recharge multiplier constant parameter that will be broadcast to all the files named in `rch`.  

If you want to manipulated the tied action, you'll have to do it after you call `pf.build_pst()` by accessing the `pf.pst.parameter_data` dataframe.  I'll add a trap for trying to pass "tied" to `add_parameters()`

**Comment by Kimmvv** [comment]
It works like a charm! 
Thousand thanks.
