### ISSUE TITLE
error setting template_files attribute on linux

### ISSUE THREAD

**Issue by hwreeves-USGS** [pypest/pyemu#230]
I'm getting an error trying to set the template_files or input_files attributes directly by
assigning a list to the attribute.  The strange thing is that I am getting the error
on linux but not windows:

I have a pst object and a list of template files, this is working on windows:
pst.template_files = template_files

but pyemu is throwing a can't set attribute error on linux, pointing to the 
line
super(Pst, self).__setattr__(key, value)

I think it may be because the decorated property for input_files doesn't have
a setter method, but I can't explain why its working on Windows.
Python 3.9 in both cases.

@mnfienen @jtwhite79

**Comment by jtwhite79** [comment]
Are you using the same version of pyemu on both systems?  The tpl/ins containers have changed recently to support the upcoming sequential da tool in pest++ - these containers are no longer simple lists, they are now dataframes accessible as `Pst.model_input_data` and `Pst.model_output_data`.  We added simple property-decorated methods for `Pst.template_files` and `Pst.instruction_files` continue to provide read access but you cant set values thru those.  Maybe thats it?

**Comment by hwreeves-USGS** [comment]
I thought I was using the  same version - using pip to install pyemu in a conda environment; but I must have an older version on the windows machine.



Howard W. Reeves
Groundwater and Watershed Modeling Team Lead
USGS Upper Midwest Water Science Center
5840 Enterprise Drive
Lansing, Michigan 48911
517-887-8914
________________________________
From: J Dub ***@***.***>
Sent: Wednesday, April 7, 2021 6:23 PM
To: pypest/pyemu ***@***.***>
Cc: Reeves, Howard W ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [pypest/pyemu] error setting template_files attribute on linux (#230)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Are you using the same version of pyemu on both systems? The tpl/ins containers have changed recently to support the upcoming sequential da tool in pest++ - these containers are no longer simple lists, they are now dataframes accessible as Pst.model_input_data and Pst.model_output_data. We added simple property-decorated methods for Pst.template_files and Pst.instruction_files continue to provide read access but you cant set values thru those. Maybe thats it?

**Comment by mnfienen** [comment]
That does seem like the issue - so if a user wants to update only the TPL or INS files, would that require updating the `pst.model_input_data` or `pst.model_output_data`  dataframe? If so, might be worth making a shortcut to allow updating that the old way as well. Seems like that workflow may be somewhat popular. I'm happy to work on that....

**Comment by hwreeves-USGS** [comment]
This works in the notebook:

pst.model_input_data.pest_file = template_files
pst.model_input_data.model_file = input_files

but it might be nice to have a setattr method for the property so you can do it directly

**Comment by mnfienen** [comment]
nice @hwreeves-USGS. Only problem I foresee is that the index of the dataframe is also the pest_file col contents, so might need to update that as well (through a setattr method, as you suggest)

**Comment by hwreeves-USGS** [comment]
I removed pyemu from my environment (pip uninstall) and installed a local version from the develop branch (pip install -e .); now the notebook is acting the same in Windows and linux-- confirms that I was using an older version.  Could including `pip pyemu` in the yml file to set up the conda environment on windows be using an older version of pyemu than linux?

**Comment by jtwhite79** [comment]
If y'all wanna add some sugar make manipulating i/o files easier, Im down, just gotta be careful that we dont bork that underlying dataframe. But, as with everything in pyemu, user beware! haha
