### ISSUE TITLE
PstFrom feature request: ability to draw different ranges of pars from same pargp

### ISSUE THREAD

**Issue by jknightusgs** [pypest/pyemu#231]
I have a group of grid scale WEL multiplier parameters initiated using PstFrom. Historical water use at some wells is more certain than others, so I'd like to reflect that in my parameter ensemble.

I've tried changing the pargp name and assigning different parlbnd and parubnd values for a subgroup of wells in pst.parameter_data, but when I call the PstFrom.draw() method, all pars in the original pargp have the same shape of distribution, which seems to default to the widest parlbnd, parubnd range of any par in the original pargp setup by PstFrom.

I modified one of the example notebooks to illustrate this issue. It should work from the examples directory of the repo.

[pstfrom_mf6_draw_inflexible_by_original_pargp.zip](https://github.com/pypest/pyemu/files/6320910/pstfrom_mf6_draw_inflexible_by_original_pargp.zip)

**Comment by jtwhite79** [comment]
@jknightusgs - we want to this use.  Lemme take a look at this issue see what its gonna take.  If you dont want correlation in the grid-scale well flux pars, then I think that will be relatively easy.  But if you want correlation (e.g. supply a geostruct) and the prior variances of the indiv pars are different, that will take a little more work.

**Comment by jtwhite79** [comment]
This should be covered now
