### ISSUE TITLE
Log file closes with exceptions

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#254]
Apparently the log file is closed when an exception is raised. In a notebook setting this requires restarting the entire process after each exception. Would be nice if there was a way to open/close the log file with each method (i.e. pf.add_parameters()) rather than start over each time a mistake is made (many for some of us!!).

**Comment by jtwhite79** [comment]
Yup- that's a problem.  Probably just want to flush the log file in that exception function rather close the log file

**Comment by briochh** [comment]
I might be inclined to add a "user beware". If a process failed, for e.g. during and add_parameters() call, it is hard to guarantee that the PEST interface hasn't been messed up. There are file generation, writing to helper files, and object attribute assignments that occur during that process and could cause issues depending on where the interruption occurs. I might be OK, but then it might not! 

We could potentially be a bit smarted about when things are written and assigned during a call? So store on temp attributes until call completion time and wrap in some try, excepts?

**Comment by jtwhite79** [comment]
That's a good point B.  It might be safest to just restart the kernel if you are using the notebook...but we can test it and see what happens!
