### ISSUE TITLE
1to1 for subset of ensemble?

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#255]
Forgive me if this is obvious (or obviously silly), but I would like to view 1to1 plot of a subset of obs. For example, view the fit of flows below some threshold:

```
threshold=100
obs=pst.observation_data
mask=[i for i in obs.index if obs.loc[i,'obsval']<threshold]
pyemu.plot_utils.ensemble_res_1to1(pst=pst,ensemble={"b":prior_obs.loc[:,mask]})
```

Is there a more obvious way to do this as is? If not, I will try to find another work around (without destroying anything :t)

**Comment by jtwhite79** [comment]
Can you reassign obs groups in the Pst instance to get this done?  I think that 1 to 1 helper makes sep plots for each obs group...

**Comment by briochh** [comment]
yup, regrouping in the pst.observation_data is the trick for this (if wanting to use `pyemu.plot_utils.ensemble_res_1to1()` ). This also related to #295 and #304 . Closing.
