### ISSUE TITLE
Zone parameterization of MF GHB file

### ISSUE THREAD

**Issue by Kimmvv** [pypest/pyemu#257]
Hi,

I am trying to add zone based parameterization for a MODFLOW GHB file using the pf.add_parameters():

    pf.add_parameters( filenames= "ref\\GHB_0000.dat",
    par_type="zone",  
    zone_array = zone_arr,
    transform="none",
    par_name_base="C",  
    pargp="C_zone",
    index_cols={"k":0, "i":1, "j":2},
    use_cols=[4],
    upper_bound=10.,  
    lower_bound=0.1  )

This produces following tpl file:

    ptf ~
    ,sidx,idx_strs,zval,pargp4,parval1_4,4
    0,"(5, 111, 255)",5111255,14.0,c_zone,1.0,~  c04  ~
    1,"(9, 201, 209)",9201209,15.0,c_zone,1.0,~  c04  ~
    2,"(0, 169, 269)",0169269,14.0,c_zone,1.0,~  c04  ~
    3,"(8, 197, 231)",8197231,15.0,c_zone,1.0,~  c04  ~

It gets the zval correct, but adds the same parameter (c04) to the entire column instead of a unique parameter for each zone, and I only get 1 parameter when I use pf.build_pst() rather than one for each zone. I've also tried the solution from https://github.com/pypest/pyemu/issues/105, but with no luck.

What am I missing?

**Comment by jtwhite79** [comment]
I cant see anything wrong with the call to `add_parameters()` but I admittedly I dont use zones or the dict-style arg for `index_cols` regularly.  Maybe @briochh has an idea?  Can you upload your model files and the script you are using?

**Comment by briochh** [comment]
Hi @Kimmvv,sorry for the delay. I am not able to run any tests right now but my initial guess would be that we are probably not supporting "zone" type pars for list-like files? I think if you switch to "grid" type then the parameter tying approach in #105 should work. 

This is a solid issue though and does raise the question of whether we should be supporting zones for list pars, especially when the user explicitly passes the kij index which could be looked up in that zone_array. Happy to receive pull requests, else I can look into it.

**Comment by Kimmvv** [comment]
Hi,
Thanks for the replies. Switching to grid type and tied parameter transform did not work for me. 

The original model files took up a lot of space, so I've tried to boil it down to a minimal working example:
[Setup GHB.zip](https://github.com/pypest/pyemu/files/6804474/Setup.GHB.zip)

Cheers

**Comment by briochh** [comment]
Thanks @Kimmvv,
That is really helpful. It looks like the issue was at the intsersection of list pars setup, in zones, while using short par names (`longnames=False`). Putting a patch together now. 

N.B. if you are using PEST++ then you can pass `longnames=True` to the initial PstFrom() call to allow pars and obs to be set up with more metadate information within the parnme and obsnme.

**Comment by briochh** [comment]
Ok @Kimmvv, can you see how you go with the latest on `develop` branch? Let me know how you get on.

**Comment by Kimmvv** [comment]
It works, now I have three different parameters to describe my general head boundary.
Thanks a lot!
