### ISSUE TITLE
Catch overhead trying to do geopsatial draws on single parameter par groups

### ISSUE THREAD

**Issue by briochh** [pypest/pyemu#266]
This may have already been addressed (@jtwhite79 ?), but there is potentially some uneccessary overhead setting up for geospatial cov/draw for par groups containing just 1 parameter. These could probs just be grouped into the diagonal draw?

**Comment by jtwhite79** [comment]
I haven't dealt with this yet but needs to be done...

**Comment by jtwhite79** [comment]
I think this usecase is covered now...
