### ISSUE TITLE
PstFrom.add_parameters; len(use_col) != len(par_name_base) should be flagged early

### ISSUE THREAD

**Issue by rosskush** [pypest/pyemu#273]
Howdy, 

when using `pf.add_parameters() `with a csv file (or possibly another text file) I noticed that when using more than one column for `use_cols `there is an error that pops up in` pst_from.py _get_tpl_or_ins_df() `that might benefit from having a raise error early on if the length of `use_cols `does not equal to the length of p`ar_name_base, upper_bound, lower_bound` and `pargp`. 

for example
```
    pf.add_parameters(filenames='kx_pst_inp.csv',
                      pargp=["kx"]*6,
                      use_cols=['low','25','50','75','high','por_tx'],
                      upper_bound=[1e10]*6,
                      lower_bound=[1e-10]*6,
                      index_cols=['form_lyr'],
                      par_name_base=["kx"],
                      par_type="grid",par_style='direct')
```

results in 
```
  File "C:/Users/rossk/Desktop/github/EvLag.2021.Recalibrate/S00_setup_pest.py", line 187, in setup_pst
    pf.add_parameters(filenames='kx_pst_inp.csv',
  File "C:\Users\rossk\miniconda3\envs\geopy38\lib\site-packages\pyemu-1.1.0-py3.8.egg\pyemu\utils\pst_from.py", line 1911, in add_parameters
    df = write_list_tpl(
  File "C:\Users\rossk\miniconda3\envs\geopy38\lib\site-packages\pyemu-1.1.0-py3.8.egg\pyemu\utils\pst_from.py", line 2781, in write_list_tpl
    df_tpl = _write_direct_df_tpl(
  File "C:\Users\rossk\miniconda3\envs\geopy38\lib\site-packages\pyemu-1.1.0-py3.8.egg\pyemu\utils\pst_from.py", line 3017, in _write_direct_df_tpl
    nname = name[iuc]
IndexError: list index out of range
```

If I simply make `par_name_bas = ['kx']*6` everything seems to work out fine.

**Comment by briochh** [comment]
Hi @rosskush, This is defo a good shout. I think the bounds lists (`upper_bound`, `lower_bound`) should automatically get filled (for better or for worse!) and `par_name_base` "should" be getting caught relatively early on `pargp` might still need an earlier catch or some default filling. From looking at your traceback it does look like `par_name_base` is sneaking through though. I'll look into it.

We could possibly be a bit smarter about filling in those lists if their lengths differ, but general assumptions about what people "probably" want can get us into trouble! Keen to hear your thoughts on this.

**Comment by rosskush** [comment]
Howdy @briochh, So in my case I was feeding in a csv with 6 columns I wanted to use. What I noticed is that since I did not make `par_name_base `a list of that length (I actually did not even change it) so pyemu was trying to iterate over "p" which is the default value. This worked for the first column but since it has only one character it did not work for the second. So maybe whatever is being used for the `upper_bound `and `lower_bound ` (I think you can use either a list of values or just a single value and pyemu will make all the parameters 


Howdy @briochh, So the easy answer would probably be something like the` _check_var_len()` black magic going on in `add_parameters()` but I see what you mean. 
```
# Process model parameter files to produce appropriate pest pars
        if index_cols is not None:  # Assume list/tabular type input files
            # ensure inputs are provided for all required cols
            ncol = len(use_cols)
            ult_lbound = _check_var_len(ult_lbound, ncol)
            ult_ubound = _check_var_len(ult_ubound, ncol)
            pargp = _check_var_len(pargp, ncol)
            lower_bound = _check_var_len(lower_bound, ncol, fill="first")
            upper_bound = _check_var_len(upper_bound, ncol, fill="first")
            if len(use_cols) != len(ult_lbound) != len(ult_ubound):
                self.logger.lraise(
                    "mismatch in number of columns to use {0} "
                    "and number of ultimate lower {0} or upper "
                    "{1} par bounds defined"
                    "".format(len(use_cols), len(ult_lbound), len(ult_ubound))
                )

            self.logger.log(
                "writing list-based template file '{0}'".format(tpl_filename)
            )
```

Maybe the better option is to modify this part of the code in` pst_from.py`?

```
# Pull out and construct name-base for parameters
        if isinstance(par_name_base, str):
            par_name_base = [par_name_base]
        # if `use_cols` is passed check number of base names is the same as cols
        if len(par_name_base) == 1:
            pass
        elif use_cols is not None and len(par_name_base) == len(use_cols):
            pass
        else:
            self.logger.lraise(
                "par_name_base should be a string, "
                "single-element container, or container of "
                "len use_cols, not '{0}'"
                "".format(str(par_name_base))
            )

```

since the default `par_name_base `is "p" which gets changed to ["p"] and has length == 1 it gets passed before python can check if `len(par_name_base) == len(use_cols)` and raises the error. I'm not sure if the 

```
        if len(par_name_base) == 1:
            pass

```

part is used for something else but I think it's safer to raise the error instead of simply filling in the lengths.

**Comment by wkitlasten** [comment]
What about something like this, assuming the "use_cols" names will make the
parnme unique

if len(par_name_base) == 1:
    par_name_base = par_name_base * len(use_cols)
