### ISSUE TITLE
Continue when non-zero returned by pyemu.os_utils.run()

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#281]
Is there a way to allow the exception raised by pyemu.os_utils.run() returning a non-zero?

Some par combinations cause my MODFLOW model to not converge. pyemu.os_utils.run() returns non-zero value, causing forward_run.py to fail. Inspecting the list file for the failed runs suggests the mass balance is fine (<0.5% usually) but the convergence criteria is not met. I could relax the convergence criteria, but I am hesitant. I could probably get convergence with more iteration, but 500 is already huge.

I think I would rather accept the results after N iterations and use "percent discrepancy" as an observation to coax the realizations into stable parameter space. Thoughts?

```
File "forward_run.py", line 271, in main
  pyemu.os_utils.run(r'mf6')
File "D:\modelling\pyemu\pyemu\utils\os_utils.py", line 127, in run
  raise Exception("run() returned non-zero: {0}".format(ret_val))
Exception: run() returned non-zero: 1
```

**Comment by jtwhite79** [comment]
Why not use convergence continue in mf6?  The latest version of mf6 returns 0 if continue is true (older versions of mf6 return nonzero if it failed to converge even with the continue option).  In general I think we want to raise an exception for a nonzero return code - explicit is better than implicit!

**Comment by wkitlasten** [comment]
Thanks man, that does it.
