### ISSUE TITLE
sc.get_removed_obs_importance should not have reset_zero_weight parameter

### ISSUE THREAD

**Issue by mnfienen** [pypest/pyemu#290]
In our fixing of `sc.get_added_obs_importance` we started enforcing a paradigm that requires that all observations in the calibration dataset have nonzero weight.

So, I propose we deprecate the `reset_zero_weight` option in `sc.get_removed_obs_importance` because there should only be non-zero weighted obs to remove anyway

**Comment by jtwhite79** [comment]
yeah, makes sense to me. I think this is a much cleaner approach...

**Comment by mnfienen** [comment]
right on - I'll do it
