### ISSUE TITLE
PESTPP-OPT: FOSM-based chance constraints and opt_recalc_chance_every()

### ISSUE THREAD

**Issue by Cecile-A-C** [pypest/pyemu#293]
Hello,

I seem to run across a problem with PESTPP-OPT when I conduct SLP and choose not to recalculate FOSM-based chance constraints at every iteration (opt_recalc_chance_every > 1). I understand that in iterations where PEST does not recalculate chance constraints, it should reuse the previous chance constraint calculations. However in my optimizations (with risk != 0.5), in iterations where PEST does not recalculate chance constraints, it instead assigns null prior & posterior standard deviations to the model-derived constraints (this shows in the .rec), and therefore finds an optimal solution corresponding to that of a risk neutral optimization (0.5).

For example this figure shows the objective function value vs the iteration number for 3 optimizations which were identical (risk=0.05) except for the opt_recalc_chance_every() variable. I can share the files if needed.
I am using pyemu version 0.9 and pestpp-5.0.11.

Thank you for your help!
Cecile
![obj_function_vs_iteration](https://user-images.githubusercontent.com/59694240/136627812-4b8b526e-fbc7-499a-a940-26d9f228405e.png)

**Comment by jtwhite79** [comment]
hey @Cecile-A-C - can you open this issue at [https://github.com/usgs/pestpp](https://github.com/usgs/pestpp).  Also, there is a new release of PEST++ (5.1.1) that includes a lot of work on the optimization tools.  If its not too much trouble, can you try running with those to verify this problem still exists?  

[https://github.com/usgs/pestpp/releases/tag/5.1.1](https://github.com/usgs/pestpp/releases/tag/5.1.1)

If it does, please share the files!
