### ISSUE TITLE
number of consec bad lambda cycles control/toggle?

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#294]
More of a question than an issue: ies ends after 4 iterations because "number of consecutive bad lambda testing cycles: 3" even though the overall phi is being reduced by 15-50% each iteration (hurray!). I don't see a way to increase the number of bad lambda testing cycles, but perhaps that would be a bad idea and this issue indicates an underlying defect (probable). Perhaps the better option is to increase the subset size at the expense of runs, play with subset how, etc to try to get my subset phi to decrease more consistently?

**Comment by jtwhite79** [comment]
Hey @wkitlasten - maybe this would be better asked on [https://github.com/usgs/pestpp](https://github.com/usgs/pestpp)? 

But to answer your question, ies uses some of the phi termination criteria as PEST, including `nphinored` (which is one of those numbers on the `* control data` section - I cant remember which one...), which ies also uses for counting "bad lambda cycles".  In the rec file you can see where ies is checking for termination:

```  
---  phi-based termination criteria check  ---  
...phiredstp:  0.01
...nphistp:  3
...nphinored (also used for consecutive bad lambda cycles):  3
```

 So if you set that number greater than `noptmax` and ies should keep rocking thru the iterations.    You can also set `ies_accept_phi_fac` to a really big number and that will tell ies to accept every iteration as "successful", but this may interfere with how ies chooses to use the partial upgrade...

Deciding when to quit iterating is super tricky.  When in doubt (and if you can afford it), I would let ies keep churning.  Then you check each iteration's results to pick the one that balances your preference for phi and parameter changes...

**Comment by wkitlasten** [comment]
Doh... sorry. So in summary: ies uses nphinored for counting "bad lambda cycles". And since this is pyemu, not pestpp:

pst.control_data.nphinored=10
