### ISSUE TITLE
Grid-based parameter covariance by zone with PstFrom

### ISSUE THREAD

**Issue by aleaf** [pypest/pyemu#298]
Hi, so i am looking to implement grid-based parameterization of aquifer properties with spatial covariance that only applies within zones (parameters in different zones are assumed to be independent). I am using ``PstFrom`` to set this up.  It is a large overly complicated model so I want to use ``PstFrom.draw(use_specsim=True)`` to avoid memory issues. It looks like the preferred way to do this is to simply call ``PstFrom.add_parameters()`` for each zone, presumably using a ``zone_array`` that only includes that zone (with the rest 0s). Something like:
```python
parameter_bounds = {
    'k': (0.01, 1000),
    ...
          }
array_files = {
    'k': sorted(glob.glob('external/k_*.dat')),
    ...  
          }    
pf = pyemu.utils.PstFrom(**args)
for tag, (lower_bound, upper_bound) in parameter_bounds.items():
    for layer, array_file in enumerate(array_files[tag]):
        all_zones_in_layer = zones3d[layer]
        unique_zones = np.unique(all_zones_in_layer)
        unique_zones = unique_zones[unique_zones > 0]
        par_name_base = f'{tag}_grid_mult'
        for zone in unique_zones:
            pargp = f'{tag}_grid_layer{layer}_zone{zone}'
            pf.add_parameters(filenames=array_file, par_type='grid', par_style='multiplier',
                  geostruct=gs,
                  par_name_base=par_name_base, pargp=pargp,
                  alt_inst_str='lay',
                  zone_array=zone_array, use_pp_zones=True,
                  upper_bound=10.,lower_bound=0.1,
                  ult_ubound=upper_bound,ult_lbound=lower_bound)
```
Is the above approach the best way to go about this? If I don't call ``pf.add_parameters()`` by zone, (if I instead simply call it by layer), the parameter groups are lumped by variable (``tag`` above) and layer, so presumably the parameters are assumed to co-vary across zones.

### Update:
when I try the above approach, pyemu is numbering the grid.csv.zone and grid.csv.tpl files as if each call to ``add_parameters()`` is for a different layer (e.g.: `k_grid_mult_lay208_grid.csv.zone`; the model has 21 layers). So it looks like the approach below is the way to go?

I was thinking I could simply continue calling ``pf.add_parameters()`` by layer (as I was doing for pilot points), and then manually edit the parameter groups later in ``PstFrom.pst.parameter_data`` (after running ``PstFrome.build_pst()``, but this didn't work, as it appears the ``PstFrom.draw()`` uses ``PstFrom.par_struct_dict`` to keep track of the parameter groupings. Editing ``PstFrom.par_struct_dict`` seems quite involved, and also takes awhile (at least in debug mode), so not sure if it is any less hassle than calling ``pf.add_parameters()`` by zone. For example (forgive the non-reproducibility):
```python
new_par_struct_dict = {}
for gs, lumped_pargp_dict in pf.par_struct_dict.items():
    new_pargp_dict = {}
    for lumped_pargp, df_list in lumped_pargp_dict.items():
        for lumped_pardata in df_list:
            new_pargps = []
            for parnme, pargp in zip(lumped_pardata['parnme'], lumped_pardata['pargp']):
                if '_grid_' in and 'multiplier' in pargp:
                    zone = int(parnme.split('_zone:')[1].split('_')[0])
                    layer = int(parnme.split('_lay:')[1].split('_')[0])
                    print(pargp)
                    pargp2 = pargp
                    new_pargp = f"{pargp.split('_zone')[0]}"
                    if 'zone' not in new_pargp:
                        new_pargp += f'_zone{zone}'
                    new_pargp += '__multiplier'
                    new_pargps.append(new_pargp)
                else:
                    new_pargps.append(pargp)
            lumped_pardata['pargp'] = new_pargps
            grouped = lumped_pardata.groupby('pargp')
            for pargp, group_pardata in grouped:
                new_pargp_dict[pargp] = [group_pardata]
    new_par_struct_dict[gs] = new_pargp_dict
```
I guess the above could conceivably be rolled in to a convenience method to allow post-hoc adjustment of parameter groups, but potential issues with different naming schemes would need to be handled or documented.

Anyways, would appreciate any advice or thoughts. Thanks in advance.
@mnfienen

**Comment by aleaf** [comment]
Hi @briochh , thanks for the reply. Yes- I was thinking that if ``PstFrom.add_parameters()`` is called by layer with a zone array, then the resulting parameters should be grouped by layer and zone (e.g. layer1-zone1, layer1-zone2, etc..). That would also make it easy to tie those parameters by layer and zone.

**Comment by jtwhite79** [comment]
@aleaf I think your approach with a separate call to `add_parameters()` for each zone is what about right.  You could also just grid-scale  multipler pars with zone type multiplier pars, which would also result in statistical independence between grid-scale pars between zones in the model inputs since the zone type pars would essentially be estimating the mean multiplier value in the zone and the grid-scale pars would be the multiplier variance around the mean. Just an idea.  Let us know how it goes - Ive been also wanting to do something similar...

**Comment by jtwhite79** [comment]
21 layers?!  yikes

Sounds like maybe we should incrementing the instance count in a better way?   I wonder if that "208" is layer 20, 8th instance maybe?

**Comment by briochh** [comment]
Hi @aleaf, very belated catch up on this one. Is this still and issue? Some of the default naming conventions have been updated since you raised this, maybe these have helped for this type of issue?

**Comment by briochh** [comment]
@aleaf closing this one for now, reopen if is still and issue
