### ISSUE TITLE
PstFrom.add_parameters() option use_pp_zones=False not working properly

### ISSUE THREAD

**Issue by jknightusgs** [pypest/pyemu#302]
Hi there,

I have a model with constant, zone, and pilot point multipliers set up via the PstFrom method. I noticed in my prior realizations that the pilot point multipliers were only being applied by pyemu where the pp_zone array parameter specified in PstFrom.add_parameters() was equal to 1.

Zones 2,3,4 were being adjusted by the constant and zone mults but not the pilot point mults. Pilot points were created throughout all 4 zones and had variable values in the parameter ensemble drawn from the PstFrom object, but were not being applied to the model input file. So I'm guessing the hang up is somewhere in pyemu.helpers.apply_array_pars()?

I am using the default setting use_pp_zones=False, which is supposed to treat all zone array values > 1 as a single zone, but results in the behavior described above. Setting use_pp_zones=True results in pilot points being applied in every zone, but interpolation is cut off at zone boundaries.

attached notebook builds a pst framework with and without multiple zone numbers specified to zone_arr, and with use_pp_zones set to True and False

It's a simple workaround to create a uniform zone array from the original to specify the former for pilot point parameterization, but just raising it here to maybe help fix the issue or clarify the add_parameters doc string.
[pyemu_pp_zone_issue.zip](https://github.com/pypest/pyemu/files/7572847/pyemu_pp_zone_issue.zip)

**Comment by jtwhite79** [comment]
@jknightusgs I'll take a look at this first thing tomorrow

**Comment by jtwhite79** [comment]
@jknightusgs  - I changed pp space to 4 (essentially one pp per zone), locked in the par values, and I get this:

![image](https://user-images.githubusercontent.com/1770912/142930727-108cbcb4-e993-4b8b-89cd-4be2c492fbae.png)


Im slow but I think that is what we want?  what am I missing?

**Comment by jknightusgs** [comment]
here is what mine looks like (top right corner is where pyemu was not applying pilot points outside of zone 1).

maybe this is a version issue. I was unable to run my script with the latest develop branch zip, but if it works for you the issue is probably on my end.
![pp_zone_comp_jk](https://user-images.githubusercontent.com/25256008/142937685-11aabb6b-8f34-43e7-9ee6-23820e3859e9.png)
:

**Comment by jtwhite79** [comment]
I commented out the other pars, removed the `ult_bounds` on the pp pars, dropped the v-lim on the plots,  and added this line:
```par.loc[:, "parval1"] = (np.arange(par.shape[0])+1) * 10```
Can you try that and see if you get the same?  Just wanna make sure there isnt some interaction thats causing the issue...

**Comment by briochh** [comment]
Hi Both,
Not sure whether they were a break or a fix but I made some changes in #299 that may relate to this issue.

**Comment by jknightusgs** [comment]
@jtwhite79 I made the changes you suggested to my script and get the same lack of pp application in zones 2-4.
![pp_zone_comp](https://user-images.githubusercontent.com/25256008/142951440-ae237942-22e0-4868-8b25-a444b498738f.png)
But my installed version of pyemu is earlier than @briochh 's changes mentioned above, and if interpolation is working as intended in the latest version this issue is probably moot, right?

**Comment by jtwhite79** [comment]
Got it - so let's call this fixed thanks to @briochh !

**Comment by briochh** [comment]
I think we all good for this. Reopen if problems resurface!
