### ISSUE TITLE
Graph 1to1 for ensembles

### ISSUE THREAD

**Issue by oscarfasanchez** [pypest/pyemu#304]
Hello, I'm trying to get a 1to1 graph from an ensemble of observations
something like this:
![image](https://user-images.githubusercontent.com/39230212/143491675-681cef8e-c428-46db-a4fb-426526c8b450.png)
the image is taken from https://www.frontiersin.org/articles/10.3389/feart.2020.565613/full  
DataSheet13_v1

and it says: pyemu.Pst.plot(kind='1to1')
from pest control file 'I:\Groundwater\Research\SAM 2015-2018\Case_studies\Ruamahanga_CS\Models\North\results\mark4_1000\cal_base_full_post_20200403\RmNorth_cal.pst'
at 2020-09-16 17:41:01.30502
so I thought it would be enough to write

case="model_pest"
m_d="master"
pst = pyemu.Pst(os.path.join(m_d,f"{case}.pst"))
pst.plot(kind="1to1")

but it shows only info from  f"{case}.base.rei"
besides that the graphics(tittles) are overlapped, and the kwargs seem to not work(or I couldn't fix it at least)

![image](https://user-images.githubusercontent.com/39230212/143494290-1d7f45cd-d4d8-4f7e-a583-1ae6787cc757.png)

I tried also:
obs_filename =case+".0.obs.csv"
obs_df = pd.read_csv(os.path.join(m_d,obs_filename),index_col=0)

ens=pyemu.ObservationEnsemble(pst, obs_df)
pyemu.plot_utils.res_1to1(pst,ensemble=ens)
 or 
ens=pyemu.ObservationEnsemble.from_csv(pst,os.path.join(m_d, obs_filename))
pyemu.plot_utils.res_1to1(pst,ensemble=ens)
and i get:

Traceback (most recent call last):

  File "<ipython-input-113-bdb24e5db8e1>", line 2, in <module>
    pyemu.plot_utils.res_1to1(pst,ensemble=ens)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyemu\plot\plot_utils.py", line 305, in res_1to1
    res = pst_utils.res_from_en(pst, kwargs["ensemble"])

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyemu\pst\pst_utils.py", line 286, in res_from_en
    modelled = df["base"]

TypeError: 'ObservationEnsemble' object is not subscriptable

similar to  issue #295  
Something wrong with my ensemble?

so...is there an easy way to get those kind of graphics?

thanks for any help

**Comment by briochh** [comment]
Hi @oscarfasanchez,

The ensemble based 1to1 plotting is a little more hidden than the regulare Pst object 1to1 hook. Checkout `pyemu.plot_utils.ensemble_res_1to1()`.
You need to pass your ensemble and pyemu.Pst object as a minimum. You should be able to pass the ensemble as a dictionary of pandas dataframes, where the key denotes the color string. 

For the plots that you reference, I would have done something like:
```
pyemu.plot_utils.ensemble_res_1to1(
                                           {'0.5': prior_oe._df, 'b': posterior_oe._df},
                                           pst=pst,  #  pyemu.Pst() object -- this defines the groupings of the obs (so you can regroup obs here if you want more/less grnularity on the plots) 
                                           filename="output_fname.pdf",
                                           base_ensemble=obsplusnoise_oe)
```
There is a bit of hueristic effort in that method for reasonable scaling of the plots but it is hard to get this to look perfect for all applications.

**Comment by oscarfasanchez** [comment]
Thankyou! it was very useful,
but @briochh ...is there a way to separate the graphs(or titles)?

**Comment by briochh** [comment]
Hi @oscarfasanchez, 

Sorry for the delay -- I think if you don't pass a `filename` to that method it should return the mpl figure objects in a list. It might be possible to split them how you want with mpl (notwithstanding the complexity around splitting up axes from figures in mpl). 

If you want different grouping of obs on each graph you can play with (temporarily) regrouping them in the pst.observation_data df before passing pst to that ensemble_res_1to1 method.  

Failing that I often find myself using the above method for a quick view and then recreating a more bespoke plot with the detail that I want. Checkout the code in that method for a bit of a template/guidance.

**Comment by oscarfasanchez** [comment]
Thankyou!
