### ISSUE TITLE
pyemu creates an external observation file with a column name AND a column obsnme

### ISSUE THREAD

**Issue by BJEANNOT0** [pypest/pyemu#311]
Hello,

today,  for the first time I used pyemu to deal with my pest control file.

I used the basic follwing command  : 

import pyemu
pst = pyemu.Pst("case.pst")
pst.control_data.noptmax = -1
pst.write("case2.pst")

I noticed that pyemu takes my external observation data section and converts it into a file named case.obs_data.csv.
The problem is that the file case.obs_data.csv. contains 2 columns regarding the name of the observation ("name" and "obsnme"), and 2 columns regarding the name of the observation group ("gorup" and "obgnme"). 

I think this is due to me using the "easy names" in external observation data section i first supplied to Pest. I also think this is not as it should be (maybe I am wrong though)

I send to you my original pest control file with its external data section : 
[case.txt](https://github.com/pypest/pyemu/files/7734819/case.txt)
[O_f_piez_A1.csv](https://github.com/pypest/pyemu/files/7734822/O_f_piez_A1.csv)
[emm_m.csv](https://github.com/pypest/pyemu/files/7734825/emm_m.csv)
[flux_depression.csv](https://github.com/pypest/pyemu/files/7734826/flux_depression.csv)
[per_l.csv](https://github.com/pypest/pyemu/files/7734827/per_l.csv)
[per_m.csv](https://github.com/pypest/pyemu/files/7734828/per_m.csv)
[por_f.csv](https://github.com/pypest/pyemu/files/7734829/por_f.csv)
[por_m.csv](https://github.com/pypest/pyemu/files/7734830/por_m.csv)
[emm_f.csv](https://github.com/pypest/pyemu/files/7734831/emm_f.csv)
[model_output.txt](https://github.com/pypest/pyemu/files/7734832/model_output.txt)
[model_input.txt](https://github.com/pypest/pyemu/files/7734833/model_input.txt)
[per_f.csv](https://github.com/pypest/pyemu/files/7734834/per_f.csv)

And i send to you the pest control file I get from running the above code. Notice how case.obs_data.csv has 2 columns for names and 2 columns for group names. I think this is not normal.

[case2.txt](https://github.com/pypest/pyemu/files/7734851/case2.txt)
[case2.par_data.csv](https://github.com/pypest/pyemu/files/7734850/case2.par_data.csv)

[case2.pargp_data.csv](https://github.com/pypest/pyemu/files/7734846/case2.pargp_data.csv)
[case2.tplfile_data.csv](https://github.com/pypest/pyemu/files/7734847/case2.tplfile_data.csv)
[case2.insfile_data.csv](https://github.com/pypest/pyemu/files/7734848/case2.insfile_data.csv)
[case2.obs_data.csv](https://github.com/pypest/pyemu/files/7734849/case2.obs_data.csv)

Best regards,

**Comment by BJEANNOT0** [comment]
I also confirm that when I use the "old" names, this problem does not appear.

**Comment by jtwhite79** [comment]
Are you using the latest develop branch version?  I think I fixed this issue a few days ago - I checked with your files and it seems to be fixed now using the latest develop.  let us know if now...

**Comment by BJEANNOT0** [comment]
Thank you for your answer.

I was at version 1.1.0 when posting the first message.
I am now at version 1.2.0. I do not know if this is the last version, although  I am nto sure.
With 1.2.0, when using  "easy" names for observations, when I try ti run the code I posted in my first message, I now get an error :
"Exception: Pst.sanity_check() error: duplicate observation names: dum"

I can confirm using the "old" names instead solves the issue.

Here are the input files : 

[case.txt](https://github.com/pypest/pyemu/files/7743776/case.txt)
(i send it as a .txt because i cannot sent directly .pst files)

[per_f.csv](https://github.com/pypest/pyemu/files/7743765/per_f.csv)
[per_l.csv](https://github.com/pypest/pyemu/files/7743766/per_l.csv)
[per_m.csv](https://github.com/pypest/pyemu/files/7743767/per_m.csv)
[por_f.csv](https://github.com/pypest/pyemu/files/7743768/por_f.csv)
[por_m.csv](https://github.com/pypest/pyemu/files/7743769/por_m.csv)
[emm_f.csv](https://github.com/pypest/pyemu/files/7743770/emm_f.csv)
[emm_m.csv](https://github.com/pypest/pyemu/files/7743771/emm_m.csv)
[flux_depression.csv](https://github.com/pypest/pyemu/files/7743772/flux_depression.csv)
[model_input.txt](https://github.com/pypest/pyemu/files/7743773/model_input.txt)
[model_output.txt](https://github.com/pypest/pyemu/files/7743774/model_output.txt)
[O_f_piez_S5.csv](https://github.com/pypest/pyemu/files/7743775/O_f_piez_S5.csv)

Here is the code that got me the error : 
import pyemu
case="case"
pst = pyemu.Pst(case+".pst")
pst.control_data.noptmax = 99
pst.write(case+".pst")

Best regards,

**Comment by jtwhite79** [comment]
actually I think this is fixed on the develop branch but we dont have a release for it yet.  Are you installing pyemu with `pip` ?  If so, I think you can do something like
```
pip install git+https://github.com/pypest/pyemu.git@develop
```
to use pip to install the latest develop branch.  I may not have the command right, but this  SO post has lots of options:

[https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)

**Comment by BJEANNOT0** [comment]
Thank you very much !
