### ISSUE TITLE
PstFrom.add_parameters: support for parameters in multiple input and tpl files

### ISSUE THREAD

**Issue by aleaf** [pypest/pyemu#313]
Sometimes we may want to include a parameter in more than one input/template file. For example, to represent a zone that extends across multiple model layers, or a crop type (that may move in space) in successive recharge arrays. This may be useful to give PEST bigger levers to adjust values systematically when the effects of adjusting values by zone and instance are too diffuse.

Currently, it seems like the paradigm of ``PstFrom.add_parameters()`` is to write one template file per call. So we can't for example supply a list of files and a 3D zone array and get a corresponding template file for each input file and zone array layer.

It seems like an easy way to achieve parameters that extend across instances may be to simply allow the user to drop the instance information from the parameter names by supplying ``None`` or an empty string to the ``alt_inst_str`` arg. Will submit a pull request shortly that attempts to do that. Does this approach make sense? Am I missing anything? Thanks for reviewing.

**Comment by briochh** [comment]
@aleaf, closing as I think your PR covered this off. Reopen if still and issue
