### ISSUE TITLE
passing `zone_array` as None for PstFrom.add_parameters 

### ISSUE THREAD

**Issue by mnfienen** [pypest/pyemu#316]
Ran into an issue when not specifying a zone array for `add_parameters` and making pilot points, would assume that it would assign pilot points throughout the layer treating as all active. However, throws an error in the following code:
```python
if not use_pp_zones and (isinstance(pp_space, int)):
    # if not using pp zones will set up pp for just one
    # zone (all non zero) -- for active domain...
    zone_array[zone_array > 0] = 1  # so can set all 
```
I recommend if `pp_space` is an `int`, and `pp_zones` is not specified, and `zone_array` is not specified, that `zone_array` be set to all 1s implying the entire domain is active. Happy to make a PR if this is workable but open to other ideas

**Comment by jtwhite79** [comment]
that sounds like a good PR to me!

**Comment by mnfienen** [comment]
done!
