### ISSUE TITLE
Error reading .rnj with pyemu.utils.helpers.jco_from_pestpp_runstorage

### ISSUE THREAD

**Issue by ckikuchi** [pypest/pyemu#324]
Hello,
I am doing a Jacobian run (NOPTMAX=-1) with pestpp-glm 5.1.6.
I would like to check the intermediate .rnj file, and used pyemu.utils.helpers.jco_from_pestpp_runstorage to read in the file, using Pyemu version 1.2.0. When I run the command, I get this message:

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyemu\utils\helpers.py", line 1145, in jco_from_pestpp_runstorage
    "more than one par diff - looks like the file wasn't created during jco filling..."

Exception: more than one par diff - looks like the file wasn't created during jco filling...

I think that this is the correct command to read in the .rnj file. Am I wrong here, or is there an incompatibility between these pestpp and pyemu versions?

Thank you!
-Colin

**Comment by briochh** [comment]
@ckikuchi, did you get to the bottom of this? closing for now. Reopen if you are still having an issue.
