### ISSUE TITLE
Pilot point location

### ISSUE THREAD

**Issue by oscarfasanchez** [pypest/pyemu#329]
Hello!
I was wondering if there is a way to add a few pilot points manually when I use pyemu.utils.PstFrom-> add_parameters.
I'm using an structured irregular grid and I need a lot of cells close to a refined zone, but I don't need a lot of pilot points, so pilot point spacing is high(I'm avoiding a lot of parameters because I'm using pest_glm).
the problem is that sometimes there are no pilot points close to the boundaries of the model, so to avoid extrapolation it would be useful to add some PP to those places.
![image](https://user-images.githubusercontent.com/39230212/156590834-94e263c2-c5b2-43bf-a6b3-de4632ab808e.png)
(in the image yellow points are field observations, green pilot points with high space and black is model domain)

if it's not possible, maybe add an option in "add parameters" to  locate pilot points at the beginning/end of the column row could be a solution in the future.

thanks for any help! 😁

**Comment by jtwhite79** [comment]
The pilot point location routine is admittedly weak.  But you can pass `pp_space` as a shapefile or dataframe (either must have the at least the fields that pilot point file would have) so that you can have more control over the pilot point locations...

**Comment by oscarfasanchez** [comment]
😁thanks for your answer !
I was looking for it, in the documentation.
https://pyemu.readthedocs.io/en/latest/autoapi/pyemu/utils/index.html?highlight=pyemu.utils.PstFrom.add_parameters#pyemu.utils.PstFrom.add_parameters
but I couldn't find it. is it outdated?, or shapefile/dataframe has to be set with other method?.
or should  i use the same ppspace as string with the pathfile?(instead int as is suggested by documentation)
thank you in advance!

**Comment by jtwhite79** [comment]
Its in the docstring for `PstFrom.add_parameters()` so Im guessing we need to check into the RTD stuff again (ugh!).  basically you can pass `pp_space` as a shapefile or csv file name (the file extension is used) or as a dataframe if you already have the pilot point location information loaded up.  In any case, the info passed to `pp_space` must have the columns that a pilot point file would have ("name", "x","y", and optionally "zone")

**Comment by oscarfasanchez** [comment]
ok, thank you!!
is that options  available in pyemu 1.0? or i have to update to 1.2?

**Comment by jtwhite79** [comment]
I recommend using the latest develop branch version but if that is not an option, then you can check in the source: if you look in the `pyemu/utils/pst_from.py` source file and you see some details about using `pp_space` in the docstring of `PstFrom.add_parameters()` you should be good to go.  But please consider using the latest develop version!  Here is what the docstring says on develop:

```
pp_space (`int`,`str` or `pd.DataFrame`): Spatial pilot point information.
                If `int` it is the spacing in rows and cols of where to place pilot points.
                If `pd.DataFrame`, then this arg is treated as a prefined set of pilot points
                and in this case, the dataframe must have "name", "x", "y", and optionally "zone" columns.
                If `str`, then an attempt is made to load a dataframe from a csv file (if `pp_space` ends with ".csv"),
                shapefile (if `pp_space` ends with ".shp") or from a pilot points file.  If `pp_space` is None,
                an integer spacing of 10 is used.  Default is None
```

**Comment by oscarfasanchez** [comment]
thankyou! I'll try to use the last version!

**Comment by jtwhite79** [comment]
I know @briochh and I have been working a lot with `PstFrom`.  Can you describe the issues you are having?  The git history is probably the only record of changes that were made...

**Comment by oscarfasanchez** [comment]
I've finally solved, pst.observation_data now has different names, playing a little with pandas was the solution.
