### ISSUE TITLE
Error with adding new column in data frame

### ISSUE THREAD

**Issue by inwoo-park** [pypest/pyemu#331]
Dear developers,

I got a error with operating "./examples/MODFLOW_to_PEST_even_more_boss.ipynb" as following.
My current version of `pandas` is 1.0.3. However, the problem occurs when the `DataFrame` appends new columns.

```bash
~/build/pyemu/pyemu/utils/geostats.py in calc_factors_grid(self, spatial_reference, zone_array, minpts_interp, maxpts_interp, search_radius, verbose, var_filename, forgive, num_threads)
1017                     else: # this method is not working at pandas version >= 1.0.3
-> 1018                         fulldf[['idist', 'inames', 'ifacts', 'err_var']] = np.array(
   1019                             [[[], [], [], np.nan]] * len(fulldf),
   1020                             dtype=object)

"None of [Index(['idist', 'inames', 'ifacts', 'err_var'], dtype='object')] are in the [columns]"
```

It seems that current pandas version >= 1.0.3 does not support following appending column method in current `DataFrame`. Therefore, I change this code as following:

```python
if pd.__version__ >= "1.0.3":
        fulldf_ = pd.DataFrame(np.array([[[], [], [], np.nan]] * len(fulldf),dtype=object),
              columns = ['idist', 'inames', 'ifacts', 'err_var'])
        fulldf = fulldf.join(fulldf_)
else: # this method is not working at pandas version >= 1.0.3
        fulldf[['idist', 'inames', 'ifacts', 'err_var']] = np.array(
              [], [], np.nan]] * len(fulldf),
              dtype=object)
```

Can I commit this bug?

Best regards,
Inwoo

**Comment by briochh** [comment]
Hi @inwoo-park, 
It does seem to be an issue in pandas 1.0.3. However, in later version of pandas the assignment we are using works just fine. You a right that if we turn it into a DataFrame first then it is safe in 1.0.3. So something like:
```
fulldf[['idist', 'inames', 'ifacts', 'err_var']] = pd.DataFrame(
                                                                        np.array( [[[], [], [], np.nan]] * len(fulldf), dtype=object) , 
                                                                        index=fulldf.index, 
                                                                        columns=['idist', 'inames', 'ifacts', 'err_var']
                                                                        )
```
works for older version of pandas (i.e 1.0.3). I am not sure where things changed. 
The array assignment that we have at the moment is quicker than constructing the DataFrame so I am keen to maintain the current code (under the assumption that this behaviour wont regress in pandas). 
Happy to look at a pull request if you want to put one together. It might be worth doing some investigation as to when pandas started supporting the straight array assignment.

Alternatively you could update your version of pandas, if you just want to side step this issue?

**Comment by inwoo-park** [comment]
Hi, @briochh.

I upgrade `pandas (>=1.4.x)` and following script works:

```python
fulldf[['idist', 'inames', 'ifacts', 'err_var']] = np.array(
              [], [], np.nan]] * len(fulldf),
              dtype=object)
```

The problem occurs with old `pandas (<=1.0.3)`.

Best regards,
Inwoo
