### ISSUE TITLE
restart of an interrupted PEST++-glm run

### ISSUE THREAD

**Issue by oscarfasanchez** [pypest/pyemu#334]
in the pest++ documentation talks a little bit about it, how can be done this in pyemu?
is there any documentation to do it?
I need to restart a glm run, because my pc shut down
thanks in Advance

**Comment by jtwhite79** [comment]
@oscarfasanchez this is tricky stuff.  In theory pestpp-glm has an automated restart that just needs the binary run storage file (.rnj or .rns). But it's in some neglect - it's complicated business.  Have you tried to restart this way?  I'd make a backup of your master dir before trying to restart...

  Where was the alg when power was lost?  If a jacobian had been filled, then you can supply that filename as base_jacobian arg.  And if some iterations had already occurred, you can update the parameter values with a par file.  If you are wanting to restart in the middle of filling the jacobian, that's harder.  Pyemu can read the binary run storage file (check out the functions in helpers for this) and give you the run results and even calculate a partial jacobian for the perturbation runs that finished.  Then you can fix these pars in the ctl file and just fill a jacobian for the remaining pars and use pyemu to stitch these jcos together.

**Comment by oscarfasanchez** [comment]
thanks for your answer @jtwhite79 
I haven't tried to restart with automated restart, because  I don't know how to do it😅. I have those files.
![image](https://user-images.githubusercontent.com/39230212/160291078-86c9a8d8-093f-450b-b65b-5b18e3401d89.png)

 in pest++ docs 6.2.12 says:
[a prematurely terminated PESTPP-GLM run can be restarted by commencing PESTPP-GLM execution using the “/r” command line switch.], and reading [5.3.3 Running PESTPP-XXX as Manager and Agent] I think it would be writing in the console something like:
pestpp-glm model_pest /r hostname ¿...?

nevertheless the pest section called   "* model command line" runs a python file called python forward_run.py (builded by pyemu)
so it has to be run by python to work(I think¿...?🤔).
so, i'm not sure how to do it

according to the rec file it was starting FOSM uncertainty analyses for iteration 1
![image](htso I have a jco file
![image](https://user-tps://user-images.githubusercontent.com/39230212/160291958-4882c84b-f63e-4cfc-99e5-2c8d55563601.png)
so I already have a complete jco file, but I would prefer to continue with the process.

regarding with "  if some iterations had already occurred, you can update the parameter values with a par file"
 do you mean that i should update initial parameters in the base model, and start a completely new optimization process?
if that's what you meant, then it would be the last option😅

so I aprecciate any comments and suggestions to restart the data assimilation process 😁

**Comment by jtwhite79** [comment]
ok in this case, looks like things were interrupted during the iteration 1 upgrade process, so all you need to do is copy the "model_pest.jco" file to a new name for safe keeping, lets say "org.jco", then supply the `base_jacobian` arg with "org.jco" which tells pestpp-glm to just use this jco, run the model once to get current residuals, then start upgrade calculations.

**Comment by oscarfasanchez** [comment]
🤔indeed it is
OPTIMISATION ITERATION NUMBER: 2                 (it starts with 1)
but 
starting FOSM uncertainty analyses for iteration 1((it starts with 0)

for some reason they have different enumeration in the rec file🤷‍♂️( i'm using pestpp-5.1.1)

assuming it was optimisation iteration 1 it would be something like:

pst = pyemu.Pst(os.path.join(m_d,"{}.pst".format(case)))

#supply the base_jacobian arg->super parameter sensitivities
pst.pestpp_options["base_jacobian"] = "org.jco" 

#run the model once to get current residuals
pst.control_data.noptmax=0
pst.write(os.path.join(pf.new_d, f"{case}.pst"))
pyemu.os_utils.run(exe_p_name + f" {case}.pst", cwd=pf.new_d)
res_file = os.path.join(pf.new_d, f"{case}.base.rei")
pst.set_res(res_file) # i'm not sure if this is what you meant

#then start upgrade calculations-->here is where I get lost the most

pyemu.os_utils.start_workers(os.path.join(t_d,"template"),
                                  exe_p_name,,
                                  os.path.join("{}.pst".format(case)),
                                  num_workers=11,
                                  worker_root=t_d,
                                  silent_master=False,
                                  verbose=True,
                                  master_dir=os.path.join(t_d,"master"))


nevertheless i think I lose one itereration in this way, because I was starting iteration 2


thanks again for your help👍

**Comment by jtwhite79** [comment]
I think things are getting tricky here between what pestpp-glm is doing vs what pyemu is doing.  You are right about setting the `base_jacobian` arg.  Looking at your directory, seems like glm got interrupted during the first iteration upgrade calculation and testing.  So that means the jco was calculated at the initial parameter estimates  so everything between the jco and ctl file should be in harmony.  When you start pestpp-glm, it will queue and run a single model run to get the current residuals (at those parameter values) and then move to the upgrades - with a residual vector and a jacobian, we can calculate upgrades.  So no need to run the model once and come back to pyemu - just go straight to start workers.  

I could be wrong here and I thought about this before....but I think the FOSM vs optimization iteration count is correct - the FOSM part happens before the upgrade solution is accepted, so that means the FOSM uncertainty estimates are calculated at the previous iteration's location in parameter space, so I think that means they are actually the previous iterations FOSM estimates.

**Comment by jtwhite79** [comment]
@oscarfasanchez Im gonna close this issue - feel free to reopen if there is more to discuss

**Comment by oscarfasanchez** [comment]
hello @jtwhite79  , I'm back!
I tried to restart my GLM run  using this tiny script(I have not tried it with workers yet)

import pyemu
import os
case="model_pest"
exe_p_name=r"C:\WRDAPP\bin\pestpp-glm"
cwd="template"
pyemu.os_utils.run(exe_p_name + f" {case} /r :4004", cwd=cwd)

but I got this error:

runfile('E:/Thesis_Runs/restart.py', wdir='E:/Thesis_Runs')
Traceback (most recent call last):

  File "E:\Thesis_Runs\restart.py", line 13, in <module>
    pyemu.os_utils.run(exe_p_name + f" {case} /r :4004", cwd=cwd)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyemu\utils\os_utils.py", line 127, in run
    raise Exception("run() returned non-zero: {0}".format(ret_val))

Exception: run() returned non-zero: 1


--------------------------------------------------------
COMMAND LINE ERROR: wrong number of args, expecting 2 (serial run mgr) or 4 (parallel run mgr)
usage:

    serial run manager:
        pestpp-xxx control_file.pst

    PANTHER master:
        pestpp-xxx control_file.pst /H :port

    PANTHER worker:
        pestpp-xxx control_file.pst /H hostname:port 

 additional options can be found in the PEST++ users manual
--------------------------------------------------------


if I change "/r" for "/h", it seems to work(but it won't restart anything, I guess), if I put "/r /h" together it doesn't find model_pest.rst
Without success, I even tried changing  cwd="template" for "master".

I have no idea what I'm doing wrong, or if it happens just because "it's in some neglect".

Thanks in advance for any help

**Comment by jtwhite79** [comment]
Now this restart in pestpp-glm is in a bit of neglect...but the reason you getting that error is that `/r` tells pestpp-glm to restart, and `/h` tells pestpp-glm to use parallel, which then requires a port number for master mode (e.g. ":4004") or hostname and port number (e.g. "localhost:4004") for worker mode.  So if you want to restart and use parallel mode, it would be `pestpp-glm my.pst /r /h :4004` for the master.

**Comment by oscarfasanchez** [comment]
@jtwhite79 bad news:(
pest stopped its execution
rec file:
![image](https://user-images.githubusercontent.com/39230212/169117012-eaa115cf-9101-44a6-bab0-af69cbdc5729.png)
output:
![image](https://user-images.githubusercontent.com/39230212/169117096-574d781c-d847-4028-92c6-b56aaadf9d67.png)
should I open an issue in the Pestpp repo?

**Comment by jtwhite79** [comment]
hmm.  I think that means the "base" parameter value run wasnt in the jco or the restart file and we got to have the that run since it is needed for the denominator.  yeah please open an issue on pest++ and I can try to look in to it

**Comment by oscarfasanchez** [comment]
@jtwhite79 Done!
