### ISSUE TITLE
Mixing multiplier / addition pars

### ISSUE THREAD

**Issue by lechambre44** [pypest/pyemu#335]
Issue found when mixing multiplier and addition style pars on ghb boundary condition.  
![pyemu_issue](https://user-images.githubusercontent.com/80859930/160518590-5f520cf0-f810-498b-8bc2-25e498281ebd.JPG)

**Comment by briochh** [comment]
Thanks @lechambre44, It looks like we are probably blindly assuming that the "style" of parameter will be consistent for a given parameter but it is (too) easy to mix operator types. At the very least I think we need to catch this and return an error to the user. If we want to support this use case (and I can think of times when we might) then we would need to establish an "order of operation". I guess the convention would be multiplier first. 

@jtwhite79 @mnfienen thoughts on this? Is there anything inherently "wrong" with mixing styles? I don't think we support mixed direct and operator styles so should we be strict with different operator styles too?

**Comment by jtwhite79** [comment]
@briochh I think it would pretty cool to mix additive and multiplier pars.  I was looking at the apply function and even tho it should mechanically work I think we do need to enforce order of operations. 

@lechambre44 - what error did you get?  Can you post the traceback?

**Comment by briochh** [comment]
@lechambre44, closing for now. I think mixed "styles" are supported (for better or worse). Reopen if this still isn't working.
