### ISSUE TITLE
Showing predictions by PESTPP-IES as an enveloppe

### ISSUE THREAD

**Issue by BJEANNOT0** [pypest/pyemu#336]
Hello,

I made a PESTPP-IES run. Now I would like to draw a chart for observations vs simulations. However, because pestpp-ies is an ensemble method, I think the most interesting chart to make is to represent pestp-ies results as an enveloppe (i.e.not by just a single line, but by a polygon with a min line, a center line and a max line. The distance between the center line and the extremes could be a given number of standard deviations, 2 for the 95% confidence interval for example)

Is there a ready to use solution that does that implemented in pyemu  ?
Thanks in advance for your help.
Best regards,

**Comment by mnfienen** [comment]
HI @BJEANNOT0  - 

You can use this function as a starting point:
`pyemu.plot_utils.ensemble_res_1to1()`
Hope that helps!

**Comment by jtwhite79** [comment]
just adding to @mnfienen - there is also an `pyemu.plot_utils.ensemble_helper` that you can multiple ensembles (or files containing them) and also pass `deter_vals` as the "obsval" values - this will get you histograms for the ensemble(s) and a solid vertical line for the obsval for each observation in the control file.  But if you want timeseries plots of observed vs simulated, you'll have to roll your own....
