### ISSUE TITLE
How do i remove a pestpp option in the pest control file ?

### ISSUE THREAD

**Issue by BJEANNOT0** [pypest/pyemu#339]
Hello,

in py pest control file, i would like to delete the keyword "ies_localizer", so that pestpp uses the default setting for this keyword.
Could you please tell me how I would do that ?
Here is some sample code about my issue :

case = "case"
pst = pyemu.Pst(case+".pst")
!the following line does not work and needs to be adapted but I do not know how
pst.pestpp_options.drop["ies_localizer"] 
pst.write(case+".pst",version=2)

Thanks in advance for your help.
Best regards,

**Comment by jtwhite79** [comment]
The `.pestpp_options` is just a standard dict so you can use `.pop`:

`pst.pestpp_options.pop("ies_localizer")`
