### ISSUE TITLE
OS paths in `Pst.model_input_data` and `Pst.model_output_data`

### ISSUE THREAD

**Issue by jtwhite79** [pypest/pyemu#349]
@briochh and @mnfienen - should we parsing (and potentially swapping) file paths in `Pst` when it is loaded and/or written?  So if you have an existing control file from linux/mac and it has paths to template/instructions and/or their counterparts, and you load this control file in windows, should we be swapping the OS path sep?

**Comment by mnfienen** [comment]
I think I favor using forward slash path sep in all cases because when we make control files on Windows they fail on *nix #sad, but forward slashes work everywhere. In fact, I might favor changing to forward on read regardless of origin. Too brash?

**Comment by jtwhite79** [comment]
I didnt know you can do forward slash on win - is that right?!  How am I just hearing about this!

**Comment by mnfienen** [comment]
I think so.....although maybe not at CMD but that shouldn't matter right?

**Comment by mnfienen** [comment]
Ack - sorry....tested again at CMD and def still needs `\`. That's what I get for not using windows much. I think powershell allows `/` so that's what I was thinking it would work. But again, python allows `/` on all systems. Do the internals of PEST++ allow it? If so, would it still work to use a common sep for paths since they are not passed to command line?

**Comment by kallejahn** [comment]
Hi @jtwhite79 and @mnfienen, I just tested an noptmax=0 iES run on my Windows machine after changing all the `\\` to `/` in the `mult2model_info.csv` (did that outside `pyemu`). As you expected Mike, it seemed to work just fine. 

It wasn't a big deal to change only the `mult2model` path separators "post-`pyemu`", but can be a bit of a pain if there are more paths that need editing. Maybe there could be a keyword (in `PstFrom`?) that would allow an override of the OS path separator?

**Comment by jtwhite79** [comment]
@kallejahn  are you using the develop version in the repo? I think the fxn that applies the info in `mult2model_info.csv` should be dealing with cross-platform path seps now...

**Comment by kallejahn** [comment]
Ah I was on an older version of the develop branch, so I just pulled the most recent. Looks like  `mult2model` seps are still `\`, when building with most recent develop, so I'm guessing that the function reading that info will be fine if running on linux?

**Comment by jtwhite79** [comment]
https://github.com/pypest/pyemu/blob/99ad2d3c6fe9bb104e30b44d1f9184f7a546f6d6/pyemu/utils/helpers.py#L3709

I think that line should be handling the OS path seps...

**Comment by briochh** [comment]
closed by #350, I think
