### ISSUE TITLE
How to add a function called by another in pf.add_py_functions()?

### ISSUE THREAD

**Issue by wkitlasten** [pypest/pyemu#360]
Is it possible to use pf.add_py_functions() to add a function that another function relies on, but not have it called in main()? For example, if "make_it_good" calls "make_it_better" but "make_it_better" should only be called by "make_it_good", how do I get "make_it_better" into my forward_run.py without having it called in main()?

```
# add the post processor function "made_it_good" from the script file "post_processors.py"
pf.add_py_function("post_processors.py","make_it_good('arg0', 'arg1')",is_pre_cmd=False)
```
Adds the function to foward_run.py and calls this from main(all good):
`make_it_good('arg0', 'arg1')`

Now I want to add "make_it_better" to forward_run.py, but NOT have it called in main()?

**Comment by jtwhite79** [comment]
Try passing the is_pre_cmd as None instead of a bool for fnxs not called directly in main...that should do it....

**Comment by wkitlasten** [comment]
Ah... right there in the docstrings... just wasn't sinking in! Thanks.
