### ISSUE TITLE
Error message using .add_parameters() though it seems to work

### ISSUE THREAD

**Issue by Smith0710** [pypest/pyemu#366]
Hi

After generating a template file using `pyemu.utils.modflow_pval_to_template_file` I get the following error message when using that template file to add parameters to the PEST data using `.add_parameters`:

"error trying to read input file with tpl file:input file EOL line 2, tpl line 3, looking for ..."

Nonetheless, the parameter data appear to be correctly added.

I am wondering if the error message is caused by me or PyEMU?

Thanks

**Comment by jtwhite79** [comment]
Should be good to go.  Pyemu is trying to read initial parameter values use the template file makers and tags - this is not guaranteed to work (and in most cases doesnt)...so what this most likely means is the initial parameter values in the control file are generic...

**Comment by Smith0710** [comment]
Thanks for this explanation. I have noticed this message in past workflows, which also work fine. Good to know I can ignore it. Cheers
