### ISSUE TITLE
Pest-sen not working with PstFrom par_style='multiplier'

### ISSUE THREAD

**Issue by jonathanqv** [pypest/pyemu#367]
Hi, I've been trying to set up my sensitivity analysis and I found out that when I run it with multipliers (default type), it creates -nan(id) in the multiplier parameters. Then I tried changing the par_style to 'direct' and it worked, but I had to troubleshoot the template too as I was using zones, and nonactive zones of my model were equal to one, which produced problems with upper and lower bounds.

Maybe it is because I am setting up a PRMS model instead of MODFLOW, or maybe I am doing something wrong.

Edit: I think it is missing the "fill_value" argument from pyemu.utils.helpers.write_zone_tpl

thanks!

**Comment by briochh** [comment]
Hi @jonathanqv, hard to say exactly what might be going on here. You might be on to something with the zone and fill thread. 

Are you able to share an example parameter file and the add_parameters() call that you are trying? I can try and look into it.

**Comment by jonathanqv** [comment]
Thanks for your reply @briochh , I had a problem with the 'transform' parameters, but it's solved. But something that also helped was to change line 2179 from pst_from.py, in which if you use an array as the input to add parameters, it assigns as default value 1 instead of the "initial_value".

Thanks!
