### ISSUE TITLE
Gridgen notebook example issue

### ISSUE THREAD

**Issue by Paszka1** [pypest/pyemu#380]
Recently I revisited the Gridgen notebook example on Github as a refresher because I wasn't successful in solving an issue with one of my projects. I noticed that it gives a `StructuredGrid' object has no attribute 'parent` error. I remember this notebook was running fine earlier with Flopy 3.3.5. Can you please confirm the issue? I have gridgen.1.0.02

**Comment by briochh** [comment]
Hi @Paszka1, this seems to be more likely a Flopy issue? Perhaps best to raise it [there](https://github.com/modflowpy/flopy/issues)
