### ISSUE TITLE
MF6 objects to PstFrom formatting

### ISSUE THREAD

**Issue by RyanConway91** [pypest/pyemu#402]
For files in the new dir made by PstFrom, ints related to l,r,c have been converted to floats. 

Original File = left, PstFrom File = right
![image](https://user-images.githubusercontent.com/25184697/213933234-e7a6f170-3e39-437b-b9bf-6bf82b3d50ba.png)

MF6 6.4.0 objects to this formatting:
![image](https://user-images.githubusercontent.com/25184697/213933257-1c12a1fe-1f77-4c78-8432-c9908c65d575.png)

**Comment by briochh** [comment]
Hi @RyanConway91, There is a bit in PstFrom to try to ensure that ints are written as ints once the processing is complete; this looks like a fairly standard use case so surprising that you are getting this issue. 

A few things to check: 0. pyEMU version, 1. your `add_paramters()` call, 2. the specific file itself.

**Comment by wkitlasten** [comment]
Could it be that in the add_parameters call you need par_type="grid"?

**Comment by briochh** [comment]
@RyanConway91, I'm closing this issue as I think the current develop branch should be addressing this. Re-open if still an issue for you.
