### ISSUE TITLE
issue with zero_order_tikhonov

### ISSUE THREAD

**Issue by hjia1005** [pypest/pyemu#410]
I used pyemu.helpers.zero_order_tikhonov(pst,parbounds=True) to set up the Tikhonov regularisation. 
All parameters, observations and prior information in pest control file are in lower letter. 
![image](https://user-images.githubusercontent.com/33449394/221487334-208f8a93-85f6-4eb1-b787-c6b203a87ec2.png)

However, when I start to run pestpp-glm, I received this error:
![image](https://user-images.githubusercontent.com/33449394/221485511-e955d748-429e-4eed-8155-b69aa4b92668.png)

I opened 008.rec and found this:
![image](https://user-images.githubusercontent.com/33449394/221487120-675d2572-fe9e-48cc-aa52-e089b7ff9ddf.png)

and this:

![image](https://user-images.githubusercontent.com/33449394/221485716-671b8157-3177-4c1c-9d97-54a2122eee67.png)

Looks like there is a conflict between upper letter and lower letter. I have no idea why those lower letter in the pest control file are converted to upper letters in the rec file.

Any way to fix it? Thanks in advance.

**Comment by hjia1005** [comment]
If I remove the below option from the pst file, then pestpp-glm runs normally without the precalculated jacobian matrix.
++base_jacobian(007_reuse.jco)

But the same thing shows up in the rec file.

![image](https://user-images.githubusercontent.com/33449394/221492562-f64c5ca4-d974-4c32-a26f-ac98ae8e30bd.png)

**Comment by jtwhite79** [comment]
Im not sure its a case issue - pest++ tries to work entirely in upper case internally (for historical reasons) while pyemu is lower case - its a heaps of fun...

what version of pestpp-glm are you using? I just tested this use case on 5.2 and its seems to find the pi equations in the jcb file...

**Comment by hjia1005** [comment]
@jtwhite79 , thanks for your reply.

Yes I was using version 5.1.21. Just downloaded the latest version 5.2.1, still have the same issue. Very strange.

**Comment by jtwhite79** [comment]
can you post your pst and jcb files so I can have a look?

**Comment by hjia1005** [comment]
Can I send them to you via email?

**Comment by hjia1005** [comment]
Solved, thank you very much! @jtwhite79
