### ISSUE TITLE
Inequality constraints for parameters

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [pypest/pyemu#417]
Hi,
I know that parameters can be tied to the parent parameters. However, I am running into an issue with max/min parameters (e.g., maximum and minimum fixation rates). How do I ensure minimum parameter is always less than or equal to the maximum parameter? In other words, parameter inequality constraints.
Many thanks,
Daniel

**Comment by jtwhite79** [comment]
The way I've seen this done usually is that you estimate the first par and a par that is the ratio of the second par to the first par.  At runtime you can calc the value of the second par as the product of the first par and the ratio value.  Then you can enforce your preferred condition with the bounds of the ratio parameter.  

You could also add the par1-par2 diff as an observation and set the obsval as the preferred condition and penalize the objective function for violations.

Just a couple of options...probably more out there...

**Comment by jtwhite79** [comment]
I know people have done the cloud/aws thing with pest++... @mnfienen and @cnicol-gwlogic are the ones who could comment with more details...

**Comment by Daniel-Trung-Nguyen** [comment]
@mnfienen, thanks a lot for sharing the information! Great implementation!
P/S: the htcondor.yml link seems to be broken.
