### ISSUE TITLE
JCO2JCO functionality in pyemu

### ISSUE THREAD

**Issue by Paszka1** [pypest/pyemu#431]
Is it possible in `pyemu` to perform a `jco2jco` type operation based on a Jacobian matrix in `jcb` file format? The `pyemu.Jco` class doesn't seem to provide such a functionality. What I would like to achieve is to modify the Jacobian matrix as a result of changing observation weights in the control file.

**Comment by briochh** [comment]
@Paszka1, This might be one for John. I can't think of a reason, off the top of my head.
