### ISSUE TITLE
ParameterEnsemble from_mixed_draws throws error when there are fixed params and fill=True

### ISSUE THREAD

**Issue by hwreeves-USGS** [pypest/pyemu#442]
I get an error from ParameterEnsemble.from_mixed_draws() when I have fixed parameters in my pst.parameter_data dataframe and fill is set to True.  

-> 1229     df.loc[pe.index, pe.columns] = pe
                    
Type Error : argument of type 'ParameterEnsemble' is not iterable

If I set fill=False, then I don't get the error but the fixed parameters are not in the ensemble, I can add them back in so that all the parameters are in the ensemble that I want pestpp-ies to use by making a list of the par names-

for k in list(fixed_dict.keys()):
    p_ensemble.loc[:,k] = pst.parameter_data.loc[k, 'parval1']

**Comment by jtwhite79** [comment]
Hey Howard - I think we have a test covering this condition:

[https://github.com/pypest/pyemu/blob/9e0a5c130e8702dcba10fad3fb0236dcc8cd4ee5/autotest/en_tests.py#L699](https://github.com/pypest/pyemu/blob/9e0a5c130e8702dcba10fad3fb0236dcc8cd4ee5/autotest/en_tests.py#L699)

and I think there were some recent patches for this problem.  Are you using the latest develop branch?

**Comment by briochh** [comment]
Hi @hwreeves-USGS, 
Have you managed to reproduce this error running the latest develop branch? 
Closing for now, but reopen is issue is still there...
