### ISSUE TITLE
Calculating phi on ObservationEnsemble

### ISSUE THREAD

**Issue by mnfienen** [pypest/pyemu#444]
the `phi_vector` property on `ObservationEnsemble` is calculating phi using the base `obsval` from the `Pst` object, but if `ObservationEnsemble` include noise obs, seems like we should calculate phi real by real right? If people agree with that idea, I can work on an update.

**Comment by mnfienen** [comment]
actually, now thinking of making a separate method `get_phi_vector_noiseobs` that allows passing in weights and/or a noise ens

**Comment by briochh** [comment]
Accomodating both weights and noise ensembles would make sense to me. I guess just need to watch for the alignment of the different ensembles. Looks like that `en.phi_vector` method could be de-looped too?

**Comment by mnfienen** [comment]
thanks @briochh - yeah, delooping might be possible in there. I'll get working on a PR with a new method

**Comment by mnfienen** [comment]
@briochh  - as part of the refactoring you recently did for pandas stuffs, are we now supporting multi-type index for reals (e.g. `base` is a `str` and all the numbered reals are `int`)? Or are we casting all index values to `str`? It seems to be the latter, but wasn't sure?

**Comment by briochh** [comment]
hey @mnfienen, I don't recall explicitly moving to support mixed types so I suspect the latter too. However, if mixed types were not causing issues we are probs not catching it. We were seeing issues where `int` mixed type entries was being cast to `float` but I think that was when on DataFrame columns, perhaps this is better handled on the index?

**Comment by mnfienen** [comment]
cool thanks @briochh  - I'll try to get a decent test for this and deal with the index (I ran into an issue when I read in a DF directly and it cast most indices to `int` but `base` was `str` so I cast all to `str` and things lined up. Stay tuned :)

**Comment by mnfienen** [comment]
ok - got something in PR #446 - looks to work
