### ISSUE TITLE
line_terminator now lineterminator

### ISSUE THREAD

**Issue by laat0003** [pypest/pyemu#445]
Howdy,

The function _write_df_tpl in helpers.py uses a deprecated kwarg that Pandas v2.0.3 no likey.
It just needs the underscore removed.
Old kwarg = "line_terminator"
New kwarg = "lineterminator"
I'm using Pyemu version 1.3.1 

Cheers,

**Comment by briochh** [comment]
Hi @laat0003,

This has been fixed on the develop branch (#416). Apologies, it looks like we haven't got around passing a version release through -- should get on that asap. In the meantime, feel free to test the latest and greatest on develop!

**Comment by laat0003** [comment]
Thanks for the quick turn around @briochh. Much appreciated.
