### ISSUE TITLE
pe.enforce() does not always update df

### ISSUE THREAD

**Issue by nicohiggs** [pypest/pyemu#510]
Ran into a situation where pe.enforce() was not enforcing bounds. After some digging I think it is related to how df.values will sometimes return a copy instead of a view (see MSeifert's answer here https://stackoverflow.com/questions/48201521/will-changes-in-dataframe-values-always-modify-the-values-in-the-data-frame and the issue here https://github.com/pandas-dev/pandas/issues/19219). Digging into _enforce_reset() you can see how if df.values returns a copy then editing the copy will not update the df.

The trouble is that when inspecting the df after calling pf.draw() in my model it appears all my types are the same, so I am not totally sure why in my case _enforce_reset() is making a copy with self._df.values which results in the df not being updated and enforce() not working. I was able to fix this locally by being more explicit in _enforce_reset() and will make a PR.

**Comment by briochh** [comment]
closed by #511 , thanks @nicohiggs
