### ISSUE TITLE
I/O operation on closed file

### ISSUE THREAD

**Issue by dejunchen83** [pypest/pyemu#515]
after pf = pstfrom got an error and stopped, the pstfrom.log file got close which leads to the following I/O error on the logger. 

`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [103], line 4
      2 print(disp1_file)
      3 # constant (coarse) scale parameters
----> 4 disp1_cst = pf.add_parameters(disp1_file,
      5                     #zone_array=ib,
      6                     par_type="constant",
      7                     geostruct=grid_gs,
      8                     par_name_base="dispsf1",
      9                     pargp="dispsf1",
     10                     index_cols=reach_ij,
     11                     use_rows=[0],
     12                     lower_bound=5.0E-6,upper_bound=5.0E-4,
     13                     ult_ubound=1.0E-7, ult_lbound=1.0E-2)

File ~/.local/lib/python3.8/site-packages/pyemu/utils/pst_from.py:1907, in PstFrom.add_parameters(self, filenames, par_type, zone_array, dist_type, sigma_range, upper_bound, lower_bound, transform, par_name_base, index_cols, use_cols, use_rows, pargp, pp_space, use_pp_zones, num_eig_kl, spatial_reference, geostruct, datetime, mfile_fmt, mfile_skip, mfile_sep, ult_ubound, ult_lbound, rebuild_pst, alt_inst_str, comment_char, par_style, initial_value)
   1905     else:
   1906         transform = 'log'
-> 1907         self.logger.statement(
   1908             "transform was not passed, setting default tranform to 'log'"
   1909         )
   1910 if transform.lower().strip() not in ["none", "log", "fixed"]:
   1911     self.logger.lraise(
   1912         "unrecognized transform ('{0}'), should be in ['none','log','fixed']".format(
   1913             transform
   1914         )
   1915     )

File ~/.local/lib/python3.8/site-packages/pyemu/logger.py:47, in Logger.statement(self, phrase)
     45     print(s, end="")
     46 if self.filename:
---> 47     self.f.write(s)
     48     self.f.flush()

ValueError: I/O operation on closed file.`

**Comment by briochh** [comment]
Hi @dejunchen83, unfortunately, the PstFrom class and methods aren't really set up to be restarted after failure. There are quite a few places where things could go missing depending on where failure occurs. It might be possible to dummy a restart by re instantiating that logger object first, with something like: `pf.logger = pyemu.Logger("PstFrom_restart.log")` but user beware!

**Comment by dejunchen83** [comment]
Thanks, 

pf.logger = pyemu.Logger("PstFrom_restart.log")

works for I/O error
