### ISSUE TITLE
numpy 2.0 incompatibility

### ISSUE THREAD

**Issue by andyrich** [pypest/pyemu#521]
# numpy dependency should be set to numpy<2.0

result when importing with numpy=2.0:
![image](https://github.com/pypest/pyemu/assets/16653125/2b21f476-cfa4-4d90-a33f-ecaf3e0fbc08)
![image](https://github.com/pypest/pyemu/assets/16653125/8ca8db7d-f402-4761-bed6-5383901af222)

result when importing with numpy<2.0
![image](https://github.com/pypest/pyemu/assets/16653125/2808624c-2331-4809-9aca-a2282df3cad8)

**Comment by jtwhite79** [comment]
Thanks Andy.  I'm not surprised there are some issues with numpy 2.  We will start working on this but in the meantime we will probably just require numpy<2
