### ISSUE TITLE
Add python function (to PstFrom.add_py_function) as a function/string. 

### ISSUE THREAD

**Issue by martinvonk** [pypest/pyemu#527]
Currently, the `PstFrom` method  `add_py_function` takes a path to a separate python source file. This python source file is read, interpreted and copied to the forward run script.  

I think it would be nice to allow for adding the code from the python source file as a string to the PstFrom class. For instance, say you have a file `_update_model.py` containing the following code:

```python
def run():
    updated_parameters = read_csv("parameters.csv")
    new_simulation = some_model.simulate(parameters=updated_parameters)
    new_simulation.to_csv("simulation.csv")
```
This file is added to the PstFrom class via:
```python
pf = PstFrom()
pf.add_py_function("_update_model.py", "run()", is_pre_cmd=None)
pf.mod_py_cmds.append("run()")
```

My proposal would be to allow to create a new method add_py_function_str:
```python
update_model_str = """
def run():
    updated_parameters = read_csv("parameters.csv")
    new_simulation = some_model.simulate(parameters=updated_parameters)
    new_simulation.to_csv("simulation.csv")
"""
pf = PstFrom()
pf.add_py_function_str(update_model_str , "run()", is_pre_cmd=None)
pf.mod_py_cmds.append("run()")
```
This way, you don't need a separate python source file per se. You only need one python script / notebook which makes examples and changing the code easier. 

Also, to implement it, the code does not need too many changes. Only the [interpretation of the file (or string)](https://github.com/pypest/pyemu/blob/5551e161bb4978c599b7352ee373b0d88d831d68/pyemu/utils/pst_from.py#L1267-L1293) has to be a separate function which is called by both `add_py_function` and `add_py_function_str`.

**Comment by martinvonk** [comment]
I figure I could also just write the string to a file and parse that to the `add_py_function` method. So if that is a better convention, this issue can be closed.

**Comment by jtwhite79** [comment]
I see what you are getting @martinvonk .  From my standpoint, I always test run the function during the setup to make sure its doing what its supposed to do - that's really why we look for an existing function.  Note that function can be in the py script that is calling pstfrom (one in the same script) but in the case of a notebook, I can see the value in not forcing the function to be in a py file.. @briochh any thoughts on this?  I reckon we could make this a user beware thing if the first arg to `add_py_function()` gives file not found...

**Comment by martinvonk** [comment]
I did not know you could do this when I made this issue. But another option would be to provide a function (callable), and use the `getsource` function from Python's built-in `inspect`library 5`inspect.getsource` to transform the function a string:

```python
def run():
    updated_parameters = read_csv("parameters.csv")
    new_simulation = some_model.simulate(parameters=updated_parameters)
    new_simulation.to_csv("simulation.csv")

pf = PstFrom()
pf.add_py_function(run, "run()", is_pre_cmd=None)
pf.mod_py_cmds.append("run()")
```

`add_py_function` then needs an if statement:
```python
from inspect import getsource

def add_py_function(self, file_name, call_str=None, is_pre_cmd=True, function_name=None):
    if callable(file_name):
        functionstr = getsource(file_name)
        # do something to let this end in the run file:
        self._function_lines_list = functionstr.splitlines() #? 
    elif isinstance(file_name, str):
        # normal behavior
```

this way you won't need a different function as I suggested as a solution when I opened the issue.

**Comment by martinvonk** [comment]
> That's a good call @martinvonk . We are using inspect in a few places already...we will get this added...unless you wanna PR it?!

I can make a PR. No problem.
