### ISSUE TITLE
ready for numpy 2?

### ISSUE THREAD

**Issue by mnfienen** [pypest/pyemu#531]
Hey @briochh - it looks like `flopy` is dialed in for `numpy 2.0` as of version 3.7.0. So.....can we pull your `numpy2` branch into `main`? At the moment, `pyemu` installed from conda-forge fails for some remaining `numpy 2` deprecations.

Thanks!

**Comment by briochh** [comment]
Hey @mnfienen, I reckon we can give it a go. We needed to wait for flopy 3.8 for some reason I don't remember. That is out now. It's makes the dependencies a little confusing going backward but should be all good going forwards.

**Comment by mnfienen** [comment]
killer @briochh  - you wanna do the honors?

**Comment by briochh** [comment]
hopefully addressed with #530

**Comment by mnfienen** [comment]
Thanks @briochh  - @jtwhite79  are we good to also bring into main?

**Comment by briochh** [comment]
@mnfienen, I can dial up a release if you guys are ok with it. Scares me a bit as there was some wrangling of the pstfrom apply methods required, and although the tests pass...

**Comment by briochh** [comment]
Just released [1.3.7](https://github.com/pypest/pyemu/tree/1.3.7) with numpy 2.0 compatibility.

**Comment by mnfienen** [comment]
thanks dude!
