### ISSUE TITLE
Pf.build_pst fails when using longnames=False plus dataframe of pilot-points

### ISSUE THREAD

**Issue by laat0003** [pypest/pyemu#541]
From the discussions section,

When using a dataframe of predefined pilot-points with longnames=False in PstFrom, the template files are created fine but the build will either (1) fail completely if only pilot-points are in the setup, or (2) continue if the setup has parameters in addition to pilot-points but it won't swap the long names for short names in the pilot-point template files. 

From the error that is reported when the build fails completely (i.e., when you only have pilot-points) it looks like no entry is being made in the full_par_dat dataframe for the tpl_filename associated with the pilot-points when they are added via a dataframe. I guess this explains why the build continues without failing if parameters other than the pilot-points are included. 

You should be able to recreate the error by simply using longnames=False, adding pilot-points from a dataframe and then building Pst.

Hope that helps.

**Comment by jtwhite79** [comment]
That def helps narrow things down - thanks @laat0003 !
