### ISSUE TITLE
Different bounds for different pp zones

### ISSUE THREAD

**Issue by reneangermeyer** [pypest/pyemu#548]
Hi everyone!

I'm trying to set up a pilot point parameter using the use_pp_zones option to represent the hydrogeologic units in my first layer. The challenge I'm facing is that, conceptually, each hydrogeologic unit has different upper and lower bounds. However, with add_parameters, I can only specify a single set of bounds for all pilot points across all zones. Is there a way to assign different bounds to different zones?

Thanks!

**Comment by briochh** [comment]
Hey @reneangermeyer ,
Unfortunately we haven't got a great mechanism for setting different bounds within a single add_parameters call. This is perhaps something we should look at. 
For now the best approach might be to use multiple calls and pass as dummy zone array of zeros and one for each zone. Not pretty but it should work.

**Comment by reneangermeyer** [comment]
Thank you! yepp, that way is cleaner and more elegant. I particularly used the second option and everything went well!
