### ISSUE TITLE
Modflow overflow

### ISSUE THREAD

**Issue by Saman-M-B** [pypest/pyemu#563]
Hello,

I'm trying to use pyemu to create a simple workflow for my transient modflow-nwt model calibration and I'm having some problems. The model is calibrated steady-state and now transfering it to transient with monthly stress-period to be calibrated for hk, vka, and sy. So I'm using zone-based parametrization which each of my model layers is divided between these zones representing hydrogeological units. My zones' hydrogeological values of K and Sy are the same within each layer (4-layer) and only their extent would change. the values below are for these zones. Initial values are steady-state calibrated values and upper and lower bounds are the ones I used for steady-state calibration also. (values in m/day)

Parameter | Upper bound | Lower bound | Initial values
hk1 | 864.00000 | 86.400000 | 97.240000
hk2 | 86.40000 | 1.728000 | 11.550000
hk3 | 1.72800 | 0.086400 | 0.086400
hk4 | 0.08640 | 0.000864 | 0.086400
vka1 | 86.40000 | 8.640000 | 48.590000
vka2 | 8.64000 | 0.172800 | 0.172800
vka3 | 0.17280 | 0.008640 | 0.008640
vka4 | 0.00864 | 0.000086 | 0.000086
sy1 | 0.30000 | 0.150000 | 0.120000
sy2 | 0.40000 | 0.200000 | 0.270000
sy3 | 0.30000 | 0.100000 | 0.250000
sy4 | 0.30000 | 0.050000 | 0.260000

Based on pestfrom, I used the code below to add each of these parameters. for zones, I manually generated them to be used here.

directory_path = os.path.join(template_ws, "ref")  
zones_prop = ["hk", "vka", "sy"]
for prop in zones_prop:
    files = [f for f in os.listdir(directory_path) if prop in f.lower()]
    Ult_vals = par_bounds[par_bounds["Parameter"].str.strip().str.contains(prop, case=False, na=False)]
    for f in files:
        f = os.path.join("ref", f)
        lay = f.split(".")[0][-1]
        zone = np.loadtxt(os.path.join(template_ws, f"Zones_Layer_{lay}.ref"))
        vals = par_bounds[par_bounds["Parameter"].str.strip() == (prop+str(lay)).strip()]
        pf.add_parameters(f,
                        zone_array=zone,
                        par_type="zone",
                        par_name_base=prop+"layer"+lay+"zone",
                        pargp=prop+lay,
                        ult_ubound=Ult_vals["Upper bound"].max(),
                        ult_lbound=Ult_vals["Lower bound"].min(),
                        transform="log",
                        par_style="multiplier"
                        )

after adding all these parameters, I later update parval1 and the upper (parubnd) and lower (parlbnd) bound values from the table.
however, when I first run the pst for noptmax=0 it runs but if I continue or run it again, I get the error below which usually means there are some values beyond logic. When I inspected the hk layer values, I realized that pst replaced the hk values with the upper bound values. still, it shouldn't be a problem cause they are not illogical but they might introduce too much water or wth. however, when I remove the "initial_value" from "pf.add_parameters", there won't be such a problem anymore. So i'm not sure what's causing it and whether I should ignore it by not setting the initial value or decreasing the upper and lower bounds. Or not so shockingly, maybe there is sth I'm doing wrong.

![image](https://github.com/user-attachments/assets/c523a7af-a5ff-4c3f-a59b-9f81d3bf9e09)

**Comment by wkitlasten** [comment]
It sounds like you might be setting the value of the multiplier parameter
to the native value of the parameter. The multiplier parameter in pst_from
should be 1 in the pst.parameter_data and is applied as per the
mult2model.csv table. If you then set it to the native parameter you will
be squaring the original native parameter value.

If you want pest to adjust the parameter value directly try
par_style=‘direct’

"Perfect spheres are pointless."

**Comment by Saman-M-B** [comment]
Yeah i get your point but that is exactly what i did first time around, to set bounds based on the multipliers' bound which i got it from the original bounds and initial values i had. Still I got this error. However, strangely enough for me when i didn't assign these parameter values, calibration ran smoothly and the resulted values are luckily within my actual parameters' range.
