### ISSUE TITLE
Add observations not adding obsval or obgnme

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#90]
This is most likely my crappy python skills, but...

I'm setting up a pest control file. I've created a timeseries of all obs well locations for all stress periods using setup_hds_timeseries(). The dataframe looks fine, and pulls head values out of the .hds file.

I run the pest helper to set up the control file. All looks good.

Then I pst.add_observations(), and write the forward run with frun. 

But in my resulting pest control file I have all of the head obs names that I put in with the timeseries appended nicely, but the obs val has gone to 10^10 and obgnme is just "obgnme". Where did my obs values go??!! 

I'm at the point where I've just trying to overwrite the obs values in the pst file (if only my df filtering skills were up to speed) but it would be good to know whether this is a bug or my ineptitude. It seems like double handling.

**Comment by RebeccaDoble** [comment]
I've ended up changing them manually in the pst object.

**Comment by RebeccaDoble** [comment]
Hi Jeremy, sorry, I didn't get an alert for your reply.
Your summary is correct. 
I tried emailing my notebook to you about a week ago, but it obviously hasn't got through. I've attached a word copy and paste, which looks crap, sorry.

How do I use the latest develop branch? Can I do a git pull? I can't access any of the pyEMU 0.5 documentation due to an insecure connection. 

I did try assigning incheck = False in the add_observations(), just in case that was the problem, but it didn't change anything.


[GISERAscript.docx](https://github.com/jtwhite79/pyemu/files/3629862/GISERAscript.docx)

**Comment by RebeccaDoble** [comment]
> 
> 
> I've ended up changing them manually in the pst object.

If anyone else actually reads this, don't change it manually. It doesn't work.

**Comment by RebeccaDoble** [comment]
So I updated my pyemu to the develop branch (version 0.8?), and..... it doesn't fix the problem. Actually it makes it worse - now I have flx_volumes and flx_constant_head and vol_constant_head also in the df, with default values for obsval and obgnme.

**Comment by RebeccaDoble** [comment]
Forgot to tag @jtwhite79 @jwhite-usgs

**Comment by jtwhite79** [comment]
Looking at that notebook export (well trying to!) it looks like inschek = False in the add _observations call which means pyemu is just parsing the ins file for observation names but not actually processing the output file with the ins for observation values.  The data frame that the setup function returns does have the extracted values in it as does the “processsd” csv file.  I can verify that pyemu instruction file processor can handle these files. Can you try using inschek =True ?  The other option is to use the data frame to set the values and group names in the pst observation data section after adding the observations .

**Comment by RebeccaDoble** [comment]
Thanks @jtwhite79. I had inschek switched off as a test before updating pyemu.

It's on again now, and after a couple of tries to get the correct file names (for some reason I had to get rid of pst_path, and hardwire the path in the ins and out file names), I'm getting the obs heads into the df. The obgnme is still obgnme, but I can work with that.

I am still not able to calculate phi though, as pyemu.os_utils.run does not run properly (probs the crappy model). The .pfm file gets to 'starting basic model IO error checking', and then nothing. There's no error messages here at all. I will have to do some more hunting.

Thanks for your help.


Hence it can't find the .base.rei file.

**Comment by RebeccaDoble** [comment]
Oops, random forgotten and un-deleted sentence at the end of the last comment.
