### ISSUE TITLE
pestpp-ies can't find .hds_timeseries.processed or .hds_timeseries.processed.ins files

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#95]
Think the title explains it. The .hds_timeseries.processed files are in the same directory as pestpp-ies and all the rest of the model files - I can see them, pestpp-ies can't. 

I have the most up to date version of pestpp-ies.exe

I've stuck them on github here: https://github.com/RebeccaDoble/gw-model 

I’m using setup_pest_interface_GISERA6.ipynb, and the working directory starts as w14c_test and ends up as w14c_template.

**Comment by jtwhite79** [comment]
Can you check the model input output section of the control file to see where the instruction file is expected to be?

**Comment by RebeccaDoble** [comment]
Thanks. You're right. The pest control file had the whole path specified. I can get it to run if I delete the paths out of the pst file manually. 

Strangely the add_observations function can't find these files unless I specify a path, even if they are in the correct model working directory. If I specify the path, the whole thing gets written into the pst file.

**Comment by wkitlasten** [comment]
Hi Rebecca,

Where are you calling the add_observations function from? You might need to
explicitly set your path in your python environment of choice. I know at
least one IDE that always gets me! Whereas the files in the pst (control)
file are all relative to the directory where pestpp-ies.exe is run.

Does that make sense?

Sent from my phone without spell checker. Please excuse my fat thumbs and
bad eyes.

**Comment by RebeccaDoble** [comment]
Thanks Wes,
Makes sense despite your thumbs and eyes. I’ve made sure that I've copied the files to the working directory where pestpp-ies is run from, and also tried to run the add_observations function from a few other directories as well. I'll just use the manual work around for the moment, unless another directory combination works.

Thanks again,
Rebecca

**Comment by RebeccaDoble** [comment]
Strangely no it doesn't. I've already tried these calls:

pst.add_observations(ins_file = ins_file, out_file=out_file,pst_path=".", inschek=True) 
pst.add_observations(ins_file = ins_file, out_file=out_file, pst_path=os.path.join(".","W14_template"), inschek=True) 
pst.add_observations(ins_file = ins_file, out_file=out_file,pst_path="W14_template", inschek=True)

And still get:
Exception: ins file not found: C:\Users\dob042\pyEMU\GW1876\activities_csiro\notebooks, W14c.hds_timeseries.processed.ins

No matter what I set pst_path to, the exception points back to the notebooks folder. Putting the full path in ("C:\Users\dob042\pyEMU\GW1876\activities_csiro\notebooks\W14_template") gives:

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

But I expect that it might revert to the same exception once the syntax error is fixed.

**Comment by RebeccaDoble** [comment]
Hey weird. If I name the in and out files as os.path.join(".","W14_template\W14c.hds_timeseries.processed") (include path, rather than just the file name)

AND make the pst_path = ".", then it executes and writes the files correctly into the pst file.

**Comment by jtwhite79** [comment]
I think that Exception is for the `ins_file` argument - it needs to be the path and filename from where the notebook/python is running to where that file resides.  Then `pst_path` is the path from where the control file resides to where the instruction file resides.  For example if the instruction file is in `template` and the control file is in `template` and python/notebook is running above `template`, then `ins_file=os.path.join("template","W14c.hds_timeseries.processed.ins")` and `pst_path="."` should get get things going

**Comment by RebeccaDoble** [comment]
Thanks. Traps for young players! I guess once more examples are publicly available, this should get a little clearer.
