### ISSUE TITLE
Getting actual head observations from actual groundwater wells into pest control file 

### ISSUE THREAD

**Issue by RebeccaDoble** [pypest/pyemu#96]
Hi clever people,

Sorry to use your bug fix zone as a help centre, but....

Which util do I need to use to get all of my head observation time series (and river flux time series) into the pest control file? I think I'm looking for something like PESTGEN. If it's in pyemu I'll use it, otherwise I'll just use boring basic dos PESTGEN.

And on that, did I miss something in the training workshop, or does the Freyberg example notebooks not have any field observations included? I can't find them anywhere in the model files or in the pest file. If not, how can you calculate a phi?

**Comment by jtwhite79** [comment]
In the class, we generated our own truth field obs and then used pandas to get them in the observation data section in the obsval column.  To do this, you need to workout the obs names that coorespond to the field observations.  Then pandas!

**Comment by RebeccaDoble** [comment]
Thanks. I do remember now.

**Comment by RebeccaDoble** [comment]
MOD2OBS has a function to interpolate the model heads when observations are between stress periods. Can pyemu also do this, or do I need to use pandas?

**Comment by jwhite-usgs** [comment]
"its on the list" - currently pandas.

**Comment by mnfienen** [comment]
it's also worth considering what an interpolated (in time) value really means. I tend to align observations to the end of a stress period whenever possible. Just a thought :)

**Comment by RebeccaDoble** [comment]
As always, it probably depends on the system and the question being asked. Which is the dominant signal - the summer/winter signal due to pumping and recharge, or the long term decline or rise due to climate, pumping and land use change? How much does it impact model outputs and prediction ranges? If your stress periods were >1yr I suspect not much at all. It would be a nice little paper. I'll add it to my never ending list!
